// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DepositoDental.Models.Entities;

[Table("cat_estados")]
[Index("Codigoestado", Name = "UQ__cat_esta__EFBB4B1BB34DCC98", IsUnique = true)]
public partial class CatEstado
{
    [Key]
    [Column("estadoid")]
    public long Estadoid { get; set; }

    [Required]
    [Column("codigoestado")]
    [StringLength(50)]
    public string Codigoestado { get; set; }

    [Required]
    [Column("nombreestado")]
    [StringLength(255)]
    public string Nombreestado { get; set; }

    [Required]
    [Column("modulo")]
    [StringLength(100)]
    public string Modulo { get; set; }

    [Column("colorhex")]
    [StringLength(7)]
    public string Colorhex { get; set; }

    [InverseProperty("Estado")]
    public virtual ICollection<ComOrdenescompra> ComOrdenescompras { get; set; } = new List<ComOrdenescompra>();

    [InverseProperty("Estado")]
    public virtual ICollection<CtaAsientoscontable> CtaAsientoscontables { get; set; } = new List<CtaAsientoscontable>();

    [InverseProperty("Estado")]
    public virtual ICollection<InvMovimiento> InvMovimientos { get; set; } = new List<InvMovimiento>();

    [InverseProperty("Estado")]
    public virtual ICollection<RrhPlanilla> RrhPlanillas { get; set; } = new List<RrhPlanilla>();

    [InverseProperty("Estado")]
    public virtual ICollection<VenCotizacione> VenCotizaciones { get; set; } = new List<VenCotizacione>();

    [InverseProperty("Estado")]
    public virtual ICollection<VenFactura> VenFacturas { get; set; } = new List<VenFactura>();

    [InverseProperty("Estado")]
    public virtual ICollection<VenPedido> VenPedidos { get; set; } = new List<VenPedido>();
}