// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DepositoDental.Models.Entities;

[Table("cat_tiposcliente")]
[Index("Codigotipo", Name = "UQ__cat_tipo__D2DC2FCB4D1CBDF4", IsUnique = true)]
public partial class CatTiposcliente
{
    [Key]
    [Column("tipoclienteid")]
    public long Tipoclienteid { get; set; }

    [Required]
    [Column("codigotipo")]
    [StringLength(50)]
    public string Codigotipo { get; set; }

    [Required]
    [Column("nombretipo")]
    [StringLength(255)]
    public string Nombretipo { get; set; }

    [Column("descuentodefecto", TypeName = "decimal(5, 2)")]
    public decimal? Descuentodefecto { get; set; }

    [InverseProperty("Tipocliente")]
    public virtual ICollection<CliCliente> CliClientes { get; set; } = new List<CliCliente>();
}