// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DepositoDental.Models.Entities;

[Table("cat_tiposdocumento")]
[Index("Codigotipo", Name = "UQ__cat_tipo__D2DC2FCBAB384E27", IsUnique = true)]
public partial class CatTiposdocumento
{
    [Key]
    [Column("tipodocumentoid")]
    public long Tipodocumentoid { get; set; }

    [Required]
    [Column("codigotipo")]
    [StringLength(50)]
    public string Codigotipo { get; set; }

    [Required]
    [Column("nombretipo")]
    [StringLength(255)]
    public string Nombretipo { get; set; }

    [Required]
    [Column("modulo")]
    [StringLength(50)]
    public string Modulo { get; set; }

    [Column("escreditofiscal")]
    public bool? Escreditofiscal { get; set; }

    [Column("afectacontabilidad")]
    public bool? Afectacontabilidad { get; set; }

    [Column("activo")]
    public bool? Activo { get; set; }
}