// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DepositoDental.Models.Entities;

[Table("cat_tiposdireccion")]
[Index("Nombre", Name = "UQ__cat_tipo__72AFBCC6E45FE15B", IsUnique = true)]
public partial class CatTiposdireccion
{
    [Key]
    [Column("tipodireccionid")]
    public int Tipodireccionid { get; set; }

    [Required]
    [Column("nombre")]
    [StringLength(50)]
    public string Nombre { get; set; }

    [Column("descripcion")]
    [StringLength(255)]
    public string Descripcion { get; set; }

    [InverseProperty("TipodireccionNavigation")]
    public virtual ICollection<CliDireccionescliente> CliDireccionesclientes { get; set; } = new List<CliDireccionescliente>();
}