// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DepositoDental.Models.Entities;

[Table("cli_clientes")]
[Index("Codigocliente", Name = "IX_cli_clientes_codigocliente")]
[Index("Tipoclienteid", "Activo", Name = "IX_cli_clientes_tipo_activo")]
[Index("Tipoclienteid", Name = "IX_cli_clientes_tipocliente")]
[Index("Codigocliente", Name = "UQ__cli_clie__5EA8EB3D3EC0CA83", IsUnique = true)]
[Index("Dui", Name = "UQ__cli_clie__D876F1BFA2CAC41E", IsUnique = true)]
[Index("Nrc", Name = "UQ__cli_clie__DF90F580C94610C7", IsUnique = true)]
[Index("Nit", Name = "UQ__cli_clie__DF97D0E4418FB65B", IsUnique = true)]
public partial class CliCliente
{
    [Key]
    [Column("clienteid")]
    public long Clienteid { get; set; }

    [Required]
    [Column("codigocliente")]
    [StringLength(50)]
    public string Codigocliente { get; set; }

    [Column("tipoclienteid")]
    public long Tipoclienteid { get; set; }

    [Required]
    [Column("razonsocial")]
    [StringLength(255)]
    public string Razonsocial { get; set; }

    [Column("nombrecomercial")]
    [StringLength(255)]
    public string Nombrecomercial { get; set; }

    [Column("dui")]
    [StringLength(15)]
    public string Dui { get; set; }

    [Column("nit")]
    [StringLength(20)]
    public string Nit { get; set; }

    [Column("nrc")]
    [StringLength(20)]
    public string Nrc { get; set; }

    [Column("escontribuyente")]
    public bool? Escontribuyente { get; set; }

    [Column("giro")]
    [StringLength(255)]
    public string Giro { get; set; }

    [Column("correoelectronico")]
    [StringLength(255)]
    public string Correoelectronico { get; set; }

    [Column("telefono1")]
    [StringLength(20)]
    public string Telefono1 { get; set; }

    [Column("whatsapp")]
    [StringLength(20)]
    public string Whatsapp { get; set; }

    [Column("direccion")]
    public string Direccion { get; set; }

    [Column("municipioid")]
    public long? Municipioid { get; set; }

    [Column("creditolimitado", TypeName = "decimal(15, 2)")]
    public decimal? Creditolimitado { get; set; }

    [Column("diasplazocredito")]
    public int? Diasplazocredito { get; set; }

    [Column("activo")]
    public bool? Activo { get; set; }

    [Column("usuariocreacion")]
    public long? Usuariocreacion { get; set; }

    [Column("fechacreacion")]
    public DateTime? Fechacreacion { get; set; }

    [InverseProperty("Cliente")]
    public virtual ICollection<CliContactoscliente> CliContactosclientes { get; set; } = new List<CliContactoscliente>();

    [InverseProperty("Cliente")]
    public virtual ICollection<CliDireccionescliente> CliDireccionesclientes { get; set; } = new List<CliDireccionescliente>();

    [ForeignKey("Municipioid")]
    [InverseProperty("CliClientes")]
    public virtual GeoMunicipio Municipio { get; set; }

    [ForeignKey("Tipoclienteid")]
    [InverseProperty("CliClientes")]
    public virtual CatTiposcliente Tipocliente { get; set; }

    [ForeignKey("Usuariocreacion")]
    [InverseProperty("CliClientes")]
    public virtual SecUsuario UsuariocreacionNavigation { get; set; }

    [InverseProperty("Cliente")]
    public virtual ICollection<VenCotizacione> VenCotizaciones { get; set; } = new List<VenCotizacione>();

    [InverseProperty("Cliente")]
    public virtual ICollection<VenFactura> VenFacturas { get; set; } = new List<VenFactura>();

    [InverseProperty("Cliente")]
    public virtual ICollection<VenPedido> VenPedidos { get; set; } = new List<VenPedido>();
}