// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DepositoDental.Models.Entities;

[Table("cli_contactosclientes")]
public partial class CliContactoscliente
{
    [Key]
    [Column("contactoid")]
    public long Contactoid { get; set; }

    [Column("clienteid")]
    public long Clienteid { get; set; }

    [Required]
    [Column("nombrecontacto")]
    [StringLength(255)]
    public string Nombrecontacto { get; set; }

    [Column("cargo")]
    [StringLength(100)]
    public string Cargo { get; set; }

    [Column("correoelectronico")]
    [StringLength(255)]
    public string Correoelectronico { get; set; }

    [Column("telefono")]
    [StringLength(20)]
    public string Telefono { get; set; }

    [Column("esprincipal")]
    public bool? Esprincipal { get; set; }

    [ForeignKey("Clienteid")]
    [InverseProperty("CliContactosclientes")]
    public virtual CliCliente Cliente { get; set; }
}