// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DepositoDental.Models.Entities;

[Table("cli_direccionesclientes")]
public partial class CliDireccionescliente
{
    [Key]
    [Column("direccionid")]
    public long Direccionid { get; set; }

    [Column("clienteid")]
    public long Clienteid { get; set; }

    [Required]
    [Column("tipodireccion")]
    [StringLength(50)]
    public string Tipodireccion { get; set; }

    [Required]
    [Column("direccion")]
    public string Direccion { get; set; }

    [Column("municipioid")]
    public long? Municipioid { get; set; }

    [Column("esprincipal")]
    public bool? Esprincipal { get; set; }

    [Column("tipodireccionid")]
    public int? Tipodireccionid { get; set; }

    [ForeignKey("Clienteid")]
    [InverseProperty("CliDireccionesclientes")]
    public virtual CliCliente Cliente { get; set; }

    [ForeignKey("Municipioid")]
    [InverseProperty("CliDireccionesclientes")]
    public virtual GeoMunicipio Municipio { get; set; }

    [ForeignKey("Tipodireccionid")]
    [InverseProperty("CliDireccionesclientes")]
    public virtual CatTiposdireccion TipodireccionNavigation { get; set; }
}