// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DepositoDental.Models.Entities;

[Table("com_ordenescompradetalle")]
public partial class ComOrdenescompradetalle
{
    [Key]
    [Column("ordencompradetalleid")]
    public long Ordencompradetalleid { get; set; }

    [Column("ordencompraid")]
    public long Ordencompraid { get; set; }

    [Column("productoid")]
    public long Productoid { get; set; }

    [Column("cantidad")]
    public int Cantidad { get; set; }

    [Column("costounitario", TypeName = "decimal(15, 4)")]
    public decimal Costounitario { get; set; }

    [ForeignKey("Ordencompraid")]
    [InverseProperty("ComOrdenescompradetalles")]
    public virtual ComOrdenescompra Ordencompra { get; set; }

    [ForeignKey("Productoid")]
    [InverseProperty("ComOrdenescompradetalles")]
    public virtual InvProducto Producto { get; set; }
}