// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DepositoDental.Models.Entities;

[Table("com_ordenescompra")]
[Index("Fechaorden", Name = "IX_com_ordenescompra_fecha")]
[Index("Proveedorid", Name = "IX_com_ordenescompra_proveedor")]
[Index("Numeroorden", Name = "UQ__com_orde__D398F1B1F5514CE1", IsUnique = true)]
public partial class ComOrdenescompra
{
    [Key]
    [Column("ordencompraid")]
    public long Ordencompraid { get; set; }

    [Required]
    [Column("numeroorden")]
    [StringLength(50)]
    public string Numeroorden { get; set; }

    [Column("proveedorid")]
    public long Proveedorid { get; set; }

    [Column("fechaorden")]
    public DateOnly Fechaorden { get; set; }

    [Column("total", TypeName = "decimal(15, 2)")]
    public decimal? Total { get; set; }

    [Column("estadoid")]
    public long Estadoid { get; set; }

    [Column("usuariocreacion")]
    public long Usuariocreacion { get; set; }

    [InverseProperty("Ordencompra")]
    public virtual ICollection<ComOrdenescompradetalle> ComOrdenescompradetalles { get; set; } = new List<ComOrdenescompradetalle>();

    [ForeignKey("Estadoid")]
    [InverseProperty("ComOrdenescompras")]
    public virtual CatEstado Estado { get; set; }

    [ForeignKey("Proveedorid")]
    [InverseProperty("ComOrdenescompras")]
    public virtual PrvProveedore Proveedor { get; set; }

    [ForeignKey("Usuariocreacion")]
    [InverseProperty("ComOrdenescompras")]
    public virtual SecUsuario UsuariocreacionNavigation { get; set; }
}