// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DepositoDental.Models.Entities;

[Table("cta_asientosdetalle")]
[Index("Asientoid", Name = "IX_cta_asientosdetalle_asiento")]
[Index("Cuentaid", Name = "IX_cta_asientosdetalle_cuenta")]
public partial class CtaAsientosdetalle
{
    [Key]
    [Column("asientodetalleid")]
    public long Asientodetalleid { get; set; }

    [Column("asientoid")]
    public long Asientoid { get; set; }

    [Column("cuentaid")]
    public long Cuentaid { get; set; }

    [Column("concepto")]
    public string Concepto { get; set; }

    [Column("debe", TypeName = "decimal(15, 2)")]
    public decimal? Debe { get; set; }

    [Column("haber", TypeName = "decimal(15, 2)")]
    public decimal? Haber { get; set; }

    [ForeignKey("Asientoid")]
    [InverseProperty("CtaAsientosdetalles")]
    public virtual CtaAsientoscontable Asiento { get; set; }

    [ForeignKey("Cuentaid")]
    [InverseProperty("CtaAsientosdetalles")]
    public virtual CtaPlancontable Cuenta { get; set; }
}