// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DepositoDental.Models.Entities;

[Table("cta_asientoscontables")]
[Index("Fechaasiento", Name = "IX_cta_asientoscontables_fecha")]
[Index("Periodoid", Name = "IX_cta_asientoscontables_periodo")]
[Index("Numeroasiento", Name = "UQ__cta_asie__73425FFE42E387D5", IsUnique = true)]
public partial class CtaAsientoscontable
{
    [Key]
    [Column("asientoid")]
    public long Asientoid { get; set; }

    [Required]
    [Column("numeroasiento")]
    [StringLength(50)]
    public string Numeroasiento { get; set; }

    [Column("periodoid")]
    public long Periodoid { get; set; }

    [Column("fechaasiento")]
    public DateOnly Fechaasiento { get; set; }

    [Required]
    [Column("concepto")]
    public string Concepto { get; set; }

    [Column("totaldebe", TypeName = "decimal(15, 2)")]
    public decimal? Totaldebe { get; set; }

    [Column("totalhaber", TypeName = "decimal(15, 2)")]
    public decimal? Totalhaber { get; set; }

    [Column("estadoid")]
    public long Estadoid { get; set; }

    [InverseProperty("Asiento")]
    public virtual ICollection<CtaAsientosdetalle> CtaAsientosdetalles { get; set; } = new List<CtaAsientosdetalle>();

    [ForeignKey("Estadoid")]
    [InverseProperty("CtaAsientoscontables")]
    public virtual CatEstado Estado { get; set; }

    [ForeignKey("Periodoid")]
    [InverseProperty("CtaAsientoscontables")]
    public virtual CtaPeriodoscontable Periodo { get; set; }
}