// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DepositoDental.Models.Entities;

[Table("cta_periodoscontables")]
[Index("Anio", "Mes", Name = "UK_cta_periodoscontables", IsUnique = true)]
public partial class CtaPeriodoscontable
{
    [Key]
    [Column("periodoid")]
    public long Periodoid { get; set; }

    [Column("anio")]
    public int Anio { get; set; }

    [Column("mes")]
    public int Mes { get; set; }

    [Column("cerrado")]
    public bool? Cerrado { get; set; }

    [InverseProperty("Periodo")]
    public virtual ICollection<CtaAsientoscontable> CtaAsientoscontables { get; set; } = new List<CtaAsientoscontable>();
}