// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DepositoDental.Models.Entities;

[Table("cta_plancontable")]
[Index("Codigocuenta", Name = "UQ__cta_plan__AF806271F680F93F", IsUnique = true)]
public partial class CtaPlancontable
{
    [Key]
    [Column("cuentaid")]
    public long Cuentaid { get; set; }

    [Required]
    [Column("codigocuenta")]
    [StringLength(50)]
    public string Codigocuenta { get; set; }

    [Required]
    [Column("nombrecuenta")]
    [StringLength(255)]
    public string Nombrecuenta { get; set; }

    [Column("cuentapadreid")]
    public long? Cuentapadreid { get; set; }

    [Column("es_cuenta_mayor")]
    public bool EsCuentaMayor { get; set; }

    [Required]
    [Column("naturaleza")]
    [StringLength(1)]
    [Unicode(false)]
    public string Naturaleza { get; set; }

    [InverseProperty("Cuenta")]
    public virtual ICollection<CtaAsientosdetalle> CtaAsientosdetalles { get; set; } = new List<CtaAsientosdetalle>();

    [ForeignKey("Cuentapadreid")]
    [InverseProperty("InverseCuentapadre")]
    public virtual CtaPlancontable Cuentapadre { get; set; }

    [InverseProperty("Cuentapadre")]
    public virtual ICollection<CtaPlancontable> InverseCuentapadre { get; set; } = new List<CtaPlancontable>();
}