// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DepositoDental.Models.Entities;

[Table("geo_departamentos")]
[Index("Paisid", Name = "IX_geo_departamentos_paisid")]
[Index("Paisid", "Nombredepartamento", Name = "UK_geo_departamentos_nombre", IsUnique = true)]
public partial class GeoDepartamento
{
    [Key]
    [Column("departamentoid")]
    public long Departamentoid { get; set; }

    [Column("paisid")]
    public long Paisid { get; set; }

    [Required]
    [Column("codigodepartamento")]
    [StringLength(50)]
    public string Codigodepartamento { get; set; }

    [Required]
    [Column("nombredepartamento")]
    [StringLength(255)]
    public string Nombredepartamento { get; set; }

    [Column("activo")]
    public bool? Activo { get; set; }

    [InverseProperty("Departamento")]
    public virtual ICollection<GeoMunicipio> GeoMunicipios { get; set; } = new List<GeoMunicipio>();

    [ForeignKey("Paisid")]
    [InverseProperty("GeoDepartamentos")]
    public virtual GeoPaise Pais { get; set; }
}