// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DepositoDental.Models.Entities;

[Table("geo_municipios")]
[Index("Departamentoid", Name = "IX_geo_municipios_departamentoid")]
[Index("Departamentoid", "Nombremunicipio", Name = "UK_geo_municipios_nombre", IsUnique = true)]
public partial class GeoMunicipio
{
    [Key]
    [Column("municipioid")]
    public long Municipioid { get; set; }

    [Column("departamentoid")]
    public long Departamentoid { get; set; }

    [Required]
    [Column("codigomunicipio")]
    [StringLength(50)]
    public string Codigomunicipio { get; set; }

    [Required]
    [Column("nombremunicipio")]
    [StringLength(255)]
    public string Nombremunicipio { get; set; }

    [Column("activo")]
    public bool? Activo { get; set; }

    [InverseProperty("Municipio")]
    public virtual ICollection<CliCliente> CliClientes { get; set; } = new List<CliCliente>();

    [InverseProperty("Municipio")]
    public virtual ICollection<CliDireccionescliente> CliDireccionesclientes { get; set; } = new List<CliDireccionescliente>();

    [ForeignKey("Departamentoid")]
    [InverseProperty("GeoMunicipios")]
    public virtual GeoDepartamento Departamento { get; set; }

    [InverseProperty("Municipio")]
    public virtual ICollection<RrhEmpleado> RrhEmpleados { get; set; } = new List<RrhEmpleado>();
}