// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DepositoDental.Models.Entities;

[Table("geo_paises")]
[Index("Codigopais", Name = "UQ__geo_pais__0D88C7E6119EDB89", IsUnique = true)]
[Index("Nombrepais", Name = "UQ__geo_pais__87FD705E742CCD38", IsUnique = true)]
public partial class GeoPaise
{
    [Key]
    [Column("paisid")]
    public long Paisid { get; set; }

    [Required]
    [Column("codigopais")]
    [StringLength(50)]
    public string Codigopais { get; set; }

    [Required]
    [Column("nombrepais")]
    [StringLength(255)]
    public string Nombrepais { get; set; }

    [Column("codigotelefonia")]
    [StringLength(10)]
    public string Codigotelefonia { get; set; }

    [Column("activo")]
    public bool? Activo { get; set; }

    [InverseProperty("Pais")]
    public virtual ICollection<GeoDepartamento> GeoDepartamentos { get; set; } = new List<GeoDepartamento>();

    [InverseProperty("Pais")]
    public virtual ICollection<PrvProveedore> PrvProveedores { get; set; } = new List<PrvProveedore>();
}