// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DepositoDental.Models.Entities;

[Table("inv_bodegas")]
[Index("Codigobodega", Name = "UQ__inv_bode__2A224F6ECEE18A0C", IsUnique = true)]
public partial class InvBodega
{
    [Key]
    [Column("bodegaid")]
    public long Bodegaid { get; set; }

    [Required]
    [Column("codigobodega")]
    [StringLength(50)]
    public string Codigobodega { get; set; }

    [Required]
    [Column("nombrebodega")]
    [StringLength(255)]
    public string Nombrebodega { get; set; }

    [Column("esprincipal")]
    public bool? Esprincipal { get; set; }

    [InverseProperty("Bodegadestino")]
    public virtual ICollection<InvMovimiento> InvMovimientoBodegadestinos { get; set; } = new List<InvMovimiento>();

    [InverseProperty("Bodegaorigen")]
    public virtual ICollection<InvMovimiento> InvMovimientoBodegaorigens { get; set; } = new List<InvMovimiento>();

    [InverseProperty("Bodega")]
    public virtual ICollection<InvStockbodega> InvStockbodegas { get; set; } = new List<InvStockbodega>();

    [InverseProperty("Bodega")]
    public virtual ICollection<InvUbicacione> InvUbicaciones { get; set; } = new List<InvUbicacione>();
}