// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DepositoDental.Models.Entities;

[Table("inv_categorias")]
[Index("Nombrecategoria", Name = "UQ__inv_cate__3385085E51F65FBB", IsUnique = true)]
public partial class InvCategoria
{
    [Key]
    [Column("categoriaid")]
    public long Categoriaid { get; set; }

    [Required]
    [Column("nombrecategoria")]
    [StringLength(255)]
    public string Nombrecategoria { get; set; }

    [Column("categoriapadreid")]
    public long? Categoriapadreid { get; set; }

    [ForeignKey("Categoriapadreid")]
    [InverseProperty("InverseCategoriapadre")]
    public virtual InvCategoria Categoriapadre { get; set; }

    [InverseProperty("Categoria")]
    public virtual ICollection<InvProducto> InvProductos { get; set; } = new List<InvProducto>();

    [InverseProperty("Categoriapadre")]
    public virtual ICollection<InvCategoria> InverseCategoriapadre { get; set; } = new List<InvCategoria>();
}