// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DepositoDental.Models.Entities;

[Table("inv_lotes")]
[Index("Productoid", "Numerolote", Name = "UK_inv_lotes", IsUnique = true)]
public partial class InvLote
{
    [Key]
    [Column("loteid")]
    public long Loteid { get; set; }

    [Column("productoid")]
    public long Productoid { get; set; }

    [Required]
    [Column("numerolote")]
    [StringLength(50)]
    public string Numerolote { get; set; }

    [Column("fechavencimiento")]
    public DateOnly? Fechavencimiento { get; set; }

    [Column("stockactual")]
    public int? Stockactual { get; set; }

    [InverseProperty("Lote")]
    public virtual ICollection<InvMovimientosdetalle> InvMovimientosdetalles { get; set; } = new List<InvMovimientosdetalle>();

    [ForeignKey("Productoid")]
    [InverseProperty("InvLotes")]
    public virtual InvProducto Producto { get; set; }
}