// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DepositoDental.Models.Entities;

[Table("inv_movimientos")]
[Index("Fechamovimiento", Name = "IX_inv_movimientos_fecha")]
[Index("Fechamovimiento", "Tipomovimientoid", Name = "IX_inv_movimientos_fecha_tipo")]
[Index("Tipomovimientoid", Name = "IX_inv_movimientos_tipo")]
[Index("Numeromovimiento", Name = "UQ__inv_movi__46CB95720B0418C1", IsUnique = true)]
public partial class InvMovimiento
{
    [Key]
    [Column("movimientoid")]
    public long Movimientoid { get; set; }

    [Required]
    [Column("numeromovimiento")]
    [StringLength(50)]
    public string Numeromovimiento { get; set; }

    [Column("tipomovimientoid")]
    public long Tipomovimientoid { get; set; }

    [Column("fechamovimiento")]
    public DateTime? Fechamovimiento { get; set; }

    [Column("bodegaorigenid")]
    public long? Bodegaorigenid { get; set; }

    [Column("bodegadestinoid")]
    public long? Bodegadestinoid { get; set; }

    [Column("observaciones")]
    public string Observaciones { get; set; }

    [Column("estadoid")]
    public long Estadoid { get; set; }

    [Column("usuariocreacion")]
    public long Usuariocreacion { get; set; }

    [ForeignKey("Bodegadestinoid")]
    [InverseProperty("InvMovimientoBodegadestinos")]
    public virtual InvBodega Bodegadestino { get; set; }

    [ForeignKey("Bodegaorigenid")]
    [InverseProperty("InvMovimientoBodegaorigens")]
    public virtual InvBodega Bodegaorigen { get; set; }

    [ForeignKey("Estadoid")]
    [InverseProperty("InvMovimientos")]
    public virtual CatEstado Estado { get; set; }

    [InverseProperty("Movimiento")]
    public virtual ICollection<InvMovimientosdetalle> InvMovimientosdetalles { get; set; } = new List<InvMovimientosdetalle>();

    [ForeignKey("Tipomovimientoid")]
    [InverseProperty("InvMovimientos")]
    public virtual InvTiposmovimiento Tipomovimiento { get; set; }

    [ForeignKey("Usuariocreacion")]
    [InverseProperty("InvMovimientos")]
    public virtual SecUsuario UsuariocreacionNavigation { get; set; }
}