// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DepositoDental.Models.Entities;

[Table("inv_movimientosdetalle")]
[Index("Movimientoid", Name = "IX_inv_movimientosdetalle_movimiento")]
[Index("Productoid", Name = "IX_inv_movimientosdetalle_producto")]
public partial class InvMovimientosdetalle
{
    [Key]
    [Column("movimientodetalleid")]
    public long Movimientodetalleid { get; set; }

    [Column("movimientoid")]
    public long Movimientoid { get; set; }

    [Column("productoid")]
    public long Productoid { get; set; }

    [Column("loteid")]
    public long? Loteid { get; set; }

    [Column("cantidad")]
    public int Cantidad { get; set; }

    [Column("costounitario", TypeName = "decimal(15, 4)")]
    public decimal? Costounitario { get; set; }

    [ForeignKey("Loteid")]
    [InverseProperty("InvMovimientosdetalles")]
    public virtual InvLote Lote { get; set; }

    [ForeignKey("Movimientoid")]
    [InverseProperty("InvMovimientosdetalles")]
    public virtual InvMovimiento Movimiento { get; set; }

    [ForeignKey("Productoid")]
    [InverseProperty("InvMovimientosdetalles")]
    public virtual InvProducto Producto { get; set; }
}