// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DepositoDental.Models.Entities;

[Table("inv_marcas")]
[Index("Nombremarca", Name = "UQ__inv_marc__A80C038FD90C0E09", IsUnique = true)]
public partial class InvMarca
{
    [Key]
    [Column("marcaid")]
    public long Marcaid { get; set; }

    [Required]
    [Column("nombremarca")]
    [StringLength(255)]
    public string Nombremarca { get; set; }

    [InverseProperty("Marca")]
    public virtual ICollection<InvProducto> InvProductos { get; set; } = new List<InvProducto>();
}