// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DepositoDental.Models.Entities;

[Table("inv_productos")]
[Index("Categoriaid", Name = "IX_inv_productos_categoria")]
[Index("Categoriaid", "Marcaid", Name = "IX_inv_productos_categoria_marca")]
[Index("Codigoproducto", Name = "IX_inv_productos_codigoproducto")]
[Index("Marcaid", Name = "IX_inv_productos_marca")]
[Index("Codigoproducto", Name = "UQ__inv_prod__605DFDFBAF32FA93", IsUnique = true)]
[Index("Codigobarras", Name = "UQ__inv_prod__72F09F4FFC0E9C3B", IsUnique = true)]
public partial class InvProducto
{
    [Key]
    [Column("productoid")]
    public long Productoid { get; set; }

    [Required]
    [Column("codigoproducto")]
    [StringLength(50)]
    public string Codigoproducto { get; set; }

    [Column("codigobarras")]
    [StringLength(50)]
    public string Codigobarras { get; set; }

    [Required]
    [Column("nombreproducto")]
    [StringLength(255)]
    public string Nombreproducto { get; set; }

    [Column("descripcion")]
    public string Descripcion { get; set; }

    [Column("categoriaid")]
    public long Categoriaid { get; set; }

    [Column("marcaid")]
    public long? Marcaid { get; set; }

    [Column("unidadmedidaid")]
    public long Unidadmedidaid { get; set; }

    [Column("costopromedio", TypeName = "decimal(15, 4)")]
    public decimal? Costopromedio { get; set; }

    [Column("precioventa1", TypeName = "decimal(15, 4)")]
    public decimal? Precioventa1 { get; set; }

    [Column("precioventa2", TypeName = "decimal(15, 4)")]
    public decimal? Precioventa2 { get; set; }

    [Column("precioventa3", TypeName = "decimal(15, 4)")]
    public decimal? Precioventa3 { get; set; }

    [Column("stockminimo")]
    public int? Stockminimo { get; set; }

    [Column("stockmaximo")]
    public int? Stockmaximo { get; set; }

    [Column("stockactual")]
    public int? Stockactual { get; set; }

    [Column("stockcomprometido")]
    public int? Stockcomprometido { get; set; }

    [Column("aplicaiva")]
    public bool? Aplicaiva { get; set; }

    [Column("porcentajeiva", TypeName = "decimal(5, 2)")]
    public decimal? Porcentajeiva { get; set; }

    [Column("codigotributario")]
    [StringLength(50)]
    public string Codigotributario { get; set; }

    [Column("manejavencimiento")]
    public bool? Manejavencimiento { get; set; }

    [Column("manejalotes")]
    public bool? Manejalotes { get; set; }

    [Column("activo")]
    public bool? Activo { get; set; }

    [Column("esservicio")]
    public bool? Esservicio { get; set; }

    [ForeignKey("Categoriaid")]
    [InverseProperty("InvProductos")]
    public virtual InvCategoria Categoria { get; set; }

    [InverseProperty("Producto")]
    public virtual ICollection<ComOrdenescompradetalle> ComOrdenescompradetalles { get; set; } = new List<ComOrdenescompradetalle>();

    [InverseProperty("Producto")]
    public virtual ICollection<InvLote> InvLotes { get; set; } = new List<InvLote>();

    [InverseProperty("Producto")]
    public virtual ICollection<InvMovimientosdetalle> InvMovimientosdetalles { get; set; } = new List<InvMovimientosdetalle>();

    [InverseProperty("Producto")]
    public virtual ICollection<InvProductosHistorico> InvProductosHistoricos { get; set; } = new List<InvProductosHistorico>();

    [InverseProperty("Producto")]
    public virtual ICollection<InvStockbodega> InvStockbodegas { get; set; } = new List<InvStockbodega>();

    [ForeignKey("Marcaid")]
    [InverseProperty("InvProductos")]
    public virtual InvMarca Marca { get; set; }

    [ForeignKey("Unidadmedidaid")]
    [InverseProperty("InvProductos")]
    public virtual InvUnidadesmedidum Unidadmedida { get; set; }

    [InverseProperty("Producto")]
    public virtual ICollection<VenCotizacionesdetalle> VenCotizacionesdetalles { get; set; } = new List<VenCotizacionesdetalle>();

    [InverseProperty("Producto")]
    public virtual ICollection<VenFacturasdetalle> VenFacturasdetalles { get; set; } = new List<VenFacturasdetalle>();

    [InverseProperty("Producto")]
    public virtual ICollection<VenPedidosdetalle> VenPedidosdetalles { get; set; } = new List<VenPedidosdetalle>();
}