// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DepositoDental.Models.Entities;

[Table("inv_productos_historico")]
public partial class InvProductosHistorico
{
    [Key]
    [Column("historicoid")]
    public long Historicoid { get; set; }

    [Column("productoid")]
    public long Productoid { get; set; }

    [Required]
    [Column("campoafectado")]
    [StringLength(100)]
    public string Campoafectado { get; set; }

    [Column("valoranterior")]
    public string Valoranterior { get; set; }

    [Column("valornuevo")]
    public string Valornuevo { get; set; }

    [Column("usuarioid")]
    public long? Usuarioid { get; set; }

    [Column("fechacambio")]
    public DateTime? Fechacambio { get; set; }

    [ForeignKey("Productoid")]
    [InverseProperty("InvProductosHistoricos")]
    public virtual InvProducto Producto { get; set; }

    [ForeignKey("Usuarioid")]
    [InverseProperty("InvProductosHistoricos")]
    public virtual SecUsuario Usuario { get; set; }
}