// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DepositoDental.Models.Entities;

[Table("inv_stockbodegas")]
[Index("Productoid", "Bodegaid", "Ubicacionid", Name = "UK_inv_stockbodegas", IsUnique = true)]
public partial class InvStockbodega
{
    [Key]
    [Column("stockbodegaid")]
    public long Stockbodegaid { get; set; }

    [Column("productoid")]
    public long Productoid { get; set; }

    [Column("bodegaid")]
    public long Bodegaid { get; set; }

    [Column("ubicacionid")]
    public long? Ubicacionid { get; set; }

    [Column("stockactual")]
    public int? Stockactual { get; set; }

    [ForeignKey("Bodegaid")]
    [InverseProperty("InvStockbodegas")]
    public virtual InvBodega Bodega { get; set; }

    [ForeignKey("Productoid")]
    [InverseProperty("InvStockbodegas")]
    public virtual InvProducto Producto { get; set; }

    [ForeignKey("Ubicacionid")]
    [InverseProperty("InvStockbodegas")]
    public virtual InvUbicacione Ubicacion { get; set; }
}