// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DepositoDental.Models.Entities;

[Table("inv_tiposmovimiento")]
[Index("Nombretipo", Name = "UQ__inv_tipo__69802A1282E5A4F9", IsUnique = true)]
public partial class InvTiposmovimiento
{
    [Key]
    [Column("tipomovimientoid")]
    public long Tipomovimientoid { get; set; }

    [Required]
    [Column("nombretipo")]
    [StringLength(255)]
    public string Nombretipo { get; set; }

    [Required]
    [Column("tipooperacion")]
    [StringLength(1)]
    [Unicode(false)]
    public string Tipooperacion { get; set; }

    [InverseProperty("Tipomovimiento")]
    public virtual ICollection<InvMovimiento> InvMovimientos { get; set; } = new List<InvMovimiento>();
}