// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DepositoDental.Models.Entities;

[Table("inv_unidadesmedida")]
[Index("Codigounidad", Name = "UQ__inv_unid__E656E2FB21E57772", IsUnique = true)]
public partial class InvUnidadesmedidum
{
    [Key]
    [Column("unidadmedidaid")]
    public long Unidadmedidaid { get; set; }

    [Required]
    [Column("codigounidad")]
    [StringLength(10)]
    public string Codigounidad { get; set; }

    [Required]
    [Column("nombreunidad")]
    [StringLength(100)]
    public string Nombreunidad { get; set; }

    [InverseProperty("Unidadmedida")]
    public virtual ICollection<InvProducto> InvProductos { get; set; } = new List<InvProducto>();
}