// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DepositoDental.Models.Entities;

[Table("inv_ubicaciones")]
[Index("Bodegaid", "Codigoubicacion", Name = "UK_inv_ubicaciones", IsUnique = true)]
public partial class InvUbicacione
{
    [Key]
    [Column("ubicacionid")]
    public long Ubicacionid { get; set; }

    [Column("bodegaid")]
    public long Bodegaid { get; set; }

    [Required]
    [Column("codigoubicacion")]
    [StringLength(50)]
    public string Codigoubicacion { get; set; }

    [Required]
    [Column("nombreubicacion")]
    [StringLength(255)]
    public string Nombreubicacion { get; set; }

    [ForeignKey("Bodegaid")]
    [InverseProperty("InvUbicaciones")]
    public virtual InvBodega Bodega { get; set; }

    [InverseProperty("Ubicacion")]
    public virtual ICollection<InvStockbodega> InvStockbodegas { get; set; } = new List<InvStockbodega>();
}