// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DepositoDental.Models.Entities;

[Table("prv_proveedores")]
[Index("Codigoproveedor", Name = "UQ__prv_prov__AD9C3B34E51280F1", IsUnique = true)]
[Index("Nrc", Name = "UQ__prv_prov__DF90F580A3AA6FD9", IsUnique = true)]
[Index("Nit", Name = "UQ__prv_prov__DF97D0E486C4738C", IsUnique = true)]
public partial class PrvProveedore
{
    [Key]
    [Column("proveedorid")]
    public long Proveedorid { get; set; }

    [Required]
    [Column("codigoproveedor")]
    [StringLength(50)]
    public string Codigoproveedor { get; set; }

    [Required]
    [Column("razonsocial")]
    [StringLength(255)]
    public string Razonsocial { get; set; }

    [Column("nombrecomercial")]
    [StringLength(255)]
    public string Nombrecomercial { get; set; }

    [Column("nit")]
    [StringLength(20)]
    public string Nit { get; set; }

    [Column("nrc")]
    [StringLength(20)]
    public string Nrc { get; set; }

    [Column("giro")]
    [StringLength(255)]
    public string Giro { get; set; }

    [Column("correoelectronico")]
    [StringLength(255)]
    public string Correoelectronico { get; set; }

    [Column("telefono1")]
    [StringLength(20)]
    public string Telefono1 { get; set; }

    [Column("direccion")]
    public string Direccion { get; set; }

    [Column("paisid")]
    public long? Paisid { get; set; }

    [Column("activo")]
    public bool? Activo { get; set; }

    [Column("usuariocreacion")]
    public long? Usuariocreacion { get; set; }

    [Column("fechacreacion")]
    public DateTime? Fechacreacion { get; set; }

    [InverseProperty("Proveedor")]
    public virtual ICollection<ComOrdenescompra> ComOrdenescompras { get; set; } = new List<ComOrdenescompra>();

    [ForeignKey("Paisid")]
    [InverseProperty("PrvProveedores")]
    public virtual GeoPaise Pais { get; set; }

    [ForeignKey("Usuariocreacion")]
    [InverseProperty("PrvProveedores")]
    public virtual SecUsuario UsuariocreacionNavigation { get; set; }
}