// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DepositoDental.Models.Entities;

[Table("rrh_cargos")]
[Index("Nombrecargo", Name = "UQ__rrh_carg__F2C2D4D89BB03C47", IsUnique = true)]
public partial class RrhCargo
{
    [Key]
    [Column("cargoid")]
    public long Cargoid { get; set; }

    [Required]
    [Column("nombrecargo")]
    [StringLength(255)]
    public string Nombrecargo { get; set; }

    [Column("descripcion")]
    public string Descripcion { get; set; }

    [InverseProperty("Cargo")]
    public virtual ICollection<RrhEmpleado> RrhEmpleados { get; set; } = new List<RrhEmpleado>();
}