// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DepositoDental.Models.Entities;

[Table("rrh_empleados")]
[Index("Correopersonal", Name = "UQ__rrh_empl__7ED5457CB3EC5305", IsUnique = true)]
[Index("Dui", Name = "UQ__rrh_empl__D876F1BF9FFA00BD", IsUnique = true)]
[Index("Nit", Name = "UQ__rrh_empl__DF97D0E47E70129B", IsUnique = true)]
[Index("Codigoempleado", Name = "UQ__rrh_empl__E53C59AFE8EAC8FF", IsUnique = true)]
public partial class RrhEmpleado
{
    [Key]
    [Column("empleadoid")]
    public long Empleadoid { get; set; }

    [Required]
    [Column("codigoempleado")]
    [StringLength(50)]
    public string Codigoempleado { get; set; }

    [Required]
    [Column("primernombre")]
    [StringLength(100)]
    public string Primernombre { get; set; }

    [Column("segundonombre")]
    [StringLength(100)]
    public string Segundonombre { get; set; }

    [Required]
    [Column("primerapellido")]
    [StringLength(100)]
    public string Primerapellido { get; set; }

    [Column("segundoapellido")]
    [StringLength(100)]
    public string Segundoapellido { get; set; }

    [Column("dui")]
    [StringLength(15)]
    public string Dui { get; set; }

    [Column("nit")]
    [StringLength(20)]
    public string Nit { get; set; }

    [Column("fechanacimiento")]
    public DateOnly? Fechanacimiento { get; set; }

    [Column("direccion")]
    public string Direccion { get; set; }

    [Column("municipioid")]
    public long? Municipioid { get; set; }

    [Column("telefono")]
    [StringLength(20)]
    public string Telefono { get; set; }

    [Column("correopersonal")]
    [StringLength(255)]
    public string Correopersonal { get; set; }

    [Column("cargoid")]
    public long? Cargoid { get; set; }

    [Column("fechaingreso")]
    public DateOnly Fechaingreso { get; set; }

    [Column("fechasalida")]
    public DateOnly? Fechasalida { get; set; }

    [Column("salariobase", TypeName = "decimal(10, 2)")]
    public decimal Salariobase { get; set; }

    [Column("activo")]
    public bool? Activo { get; set; }

    [Column("usuarioid")]
    public long? Usuarioid { get; set; }

    [ForeignKey("Cargoid")]
    [InverseProperty("RrhEmpleados")]
    public virtual RrhCargo Cargo { get; set; }

    [ForeignKey("Municipioid")]
    [InverseProperty("RrhEmpleados")]
    public virtual GeoMunicipio Municipio { get; set; }

    [InverseProperty("Empleado")]
    public virtual ICollection<RrhPlanillasdetalle> RrhPlanillasdetalles { get; set; } = new List<RrhPlanillasdetalle>();

    [ForeignKey("Usuarioid")]
    [InverseProperty("RrhEmpleados")]
    public virtual SecUsuario Usuario { get; set; }
}