// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DepositoDental.Models.Entities;

[Table("rrh_planillasdetalle")]
public partial class RrhPlanillasdetalle
{
    [Key]
    [Column("planilladetalleid")]
    public long Planilladetalleid { get; set; }

    [Column("planillaid")]
    public long Planillaid { get; set; }

    [Column("empleadoid")]
    public long Empleadoid { get; set; }

    [Column("salariobruto", TypeName = "decimal(10, 2)")]
    public decimal? Salariobruto { get; set; }

    [Column("descuentoisss", TypeName = "decimal(10, 2)")]
    public decimal? Descuentoisss { get; set; }

    [Column("descuentoafp", TypeName = "decimal(10, 2)")]
    public decimal? Descuentoafp { get; set; }

    [Column("descuentorenta", TypeName = "decimal(10, 2)")]
    public decimal? Descuentorenta { get; set; }

    [Column("otrosdescuentos", TypeName = "decimal(10, 2)")]
    public decimal? Otrosdescuentos { get; set; }

    [Column("bonificaciones", TypeName = "decimal(10, 2)")]
    public decimal? Bonificaciones { get; set; }

    [Column("salarioliquido", TypeName = "decimal(10, 2)")]
    public decimal? Salarioliquido { get; set; }

    [ForeignKey("Empleadoid")]
    [InverseProperty("RrhPlanillasdetalles")]
    public virtual RrhEmpleado Empleado { get; set; }

    [ForeignKey("Planillaid")]
    [InverseProperty("RrhPlanillasdetalles")]
    public virtual RrhPlanilla Planilla { get; set; }
}