// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DepositoDental.Models.Entities;

[Table("rrh_planillas")]
public partial class RrhPlanilla
{
    [Key]
    [Column("planillaid")]
    public long Planillaid { get; set; }

    [Column("tipoplanillaid")]
    public long Tipoplanillaid { get; set; }

    [Column("fechainicio")]
    public DateOnly Fechainicio { get; set; }

    [Column("fechafin")]
    public DateOnly Fechafin { get; set; }

    [Column("fechapago")]
    public DateOnly? Fechapago { get; set; }

    [Column("totaldescuentos", TypeName = "decimal(15, 2)")]
    public decimal? Totaldescuentos { get; set; }

    [Column("totalingresos", TypeName = "decimal(15, 2)")]
    public decimal? Totalingresos { get; set; }

    [Column("totalpagar", TypeName = "decimal(15, 2)")]
    public decimal? Totalpagar { get; set; }

    [Column("estadoid")]
    public long Estadoid { get; set; }

    [ForeignKey("Estadoid")]
    [InverseProperty("RrhPlanillas")]
    public virtual CatEstado Estado { get; set; }

    [InverseProperty("Planilla")]
    public virtual ICollection<RrhPlanillasdetalle> RrhPlanillasdetalles { get; set; } = new List<RrhPlanillasdetalle>();

    [ForeignKey("Tipoplanillaid")]
    [InverseProperty("RrhPlanillas")]
    public virtual RrhTiposplanilla Tipoplanilla { get; set; }
}