// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DepositoDental.Models.Entities;

[Table("rrh_tiposplanilla")]
[Index("Nombretipo", Name = "UQ__rrh_tipo__69802A1233FDF5AB", IsUnique = true)]
public partial class RrhTiposplanilla
{
    [Key]
    [Column("tipoplanillaid")]
    public long Tipoplanillaid { get; set; }

    [Required]
    [Column("nombretipo")]
    [StringLength(50)]
    public string Nombretipo { get; set; }

    [Column("diaspago")]
    public int Diaspago { get; set; }

    [InverseProperty("Tipoplanilla")]
    public virtual ICollection<RrhPlanilla> RrhPlanillas { get; set; } = new List<RrhPlanilla>();
}