// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DepositoDental.Models.Entities;

[Table("sec_permisos")]
[Index("Nombrepermiso", Name = "UQ__sec_perm__330B9B707852FCF3", IsUnique = true)]
public partial class SecPermiso
{
    [Key]
    [Column("permisoid")]
    public long Permisoid { get; set; }

    [Required]
    [Column("nombrepermiso")]
    [StringLength(255)]
    public string Nombrepermiso { get; set; }

    [Column("descripcion")]
    public string Descripcion { get; set; }

    [Required]
    [Column("modulo")]
    [StringLength(100)]
    public string Modulo { get; set; }

    [Required]
    [Column("accion")]
    [StringLength(50)]
    public string Accion { get; set; }

    [Column("activo")]
    public bool? Activo { get; set; }

    [InverseProperty("Permiso")]
    public virtual ICollection<SecRolpermiso> SecRolpermisos { get; set; } = new List<SecRolpermiso>();
}