// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DepositoDental.Models.Entities;

[Table("sec_rolpermisos")]
[Index("Rolid", "Permisoid", Name = "UK_sec_rolpermisos", IsUnique = true)]
public partial class SecRolpermiso
{
    [Key]
    [Column("rolpermisoid")]
    public long Rolpermisoid { get; set; }

    [Column("rolid")]
    public long Rolid { get; set; }

    [Column("permisoid")]
    public long Permisoid { get; set; }

    [Column("fechaasignacion")]
    public DateTime? Fechaasignacion { get; set; }

    [ForeignKey("Permisoid")]
    [InverseProperty("SecRolpermisos")]
    public virtual SecPermiso Permiso { get; set; }

    [ForeignKey("Rolid")]
    [InverseProperty("SecRolpermisos")]
    public virtual SecRole Rol { get; set; }
}