// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DepositoDental.Models.Entities;

[Table("sec_roles")]
[Index("Nombrerol", Name = "UQ__sec_role__2F87B02ED0250DC4", IsUnique = true)]
public partial class SecRole
{
    [Key]
    [Column("rolid")]
    public long Rolid { get; set; }

    [Required]
    [Column("nombrerol")]
    [StringLength(255)]
    public string Nombrerol { get; set; }

    [Column("descripcion")]
    public string Descripcion { get; set; }

    [Column("activo")]
    public bool? Activo { get; set; }

    [InverseProperty("Rol")]
    public virtual ICollection<SecRolpermiso> SecRolpermisos { get; set; } = new List<SecRolpermiso>();

    [InverseProperty("Rol")]
    public virtual ICollection<SecUsuariorole> SecUsuarioroles { get; set; } = new List<SecUsuariorole>();
}