// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DepositoDental.Models.Entities;

[Table("sec_sesiones")]
[Index("Tokensesion", Name = "IX_sec_sesiones_token")]
[Index("Usuarioid", Name = "IX_sec_sesiones_usuarioid")]
[Index("Tokensesion", Name = "UQ__sec_sesi__2E768E6A8A4DC6FF", IsUnique = true)]
public partial class SecSesione
{
    [Key]
    [Column("sesionid")]
    public long Sesionid { get; set; }

    [Column("usuarioid")]
    public long Usuarioid { get; set; }

    [Required]
    [Column("tokensesion")]
    [StringLength(255)]
    public string Tokensesion { get; set; }

    [Column("fechaexpiracion")]
    public DateTime Fechaexpiracion { get; set; }

    [Column("direccionip")]
    [StringLength(45)]
    public string Direccionip { get; set; }

    [Column("activa")]
    public bool? Activa { get; set; }

    [ForeignKey("Usuarioid")]
    [InverseProperty("SecSesiones")]
    public virtual SecUsuario Usuario { get; set; }
}