// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DepositoDental.Models.Entities;

[Table("sec_usuarios")]
[Index("Correoelectronico", Name = "IX_sec_usuarios_correo")]
[Index("Nombreusuario", Name = "IX_sec_usuarios_nombreusuario")]
[Index("Nombreusuario", Name = "UQ__sec_usua__F5D9BCAA9CD154F9", IsUnique = true)]
[Index("Correoelectronico", Name = "UQ__sec_usua__FA921E7F1B9FBF4C", IsUnique = true)]
public partial class SecUsuario
{
    [Key]
    [Column("usuarioid")]
    public long Usuarioid { get; set; }

    [Required]
    [Column("nombreusuario")]
    [StringLength(255)]
    public string Nombreusuario { get; set; }

    [Required]
    [Column("correoelectronico")]
    [StringLength(255)]
    public string Correoelectronico { get; set; }

    [Required]
    [Column("passwordhash")]
    [StringLength(255)]
    public string Passwordhash { get; set; }

    [Required]
    [Column("sal")]
    [StringLength(255)]
    public string Sal { get; set; }

    [Required]
    [Column("primernombre")]
    [StringLength(100)]
    public string Primernombre { get; set; }

    [Required]
    [Column("primerapellido")]
    [StringLength(100)]
    public string Primerapellido { get; set; }

    [Column("telefono")]
    [StringLength(20)]
    public string Telefono { get; set; }

    [Column("activo")]
    public bool? Activo { get; set; }

    [Column("ultimoacceso")]
    public DateTime? Ultimoacceso { get; set; }

    [Column("intentoslogin")]
    public int? Intentoslogin { get; set; }

    [Column("bloqueado")]
    public bool? Bloqueado { get; set; }

    [InverseProperty("UsuariocreacionNavigation")]
    public virtual ICollection<CliCliente> CliClientes { get; set; } = new List<CliCliente>();

    [InverseProperty("UsuariocreacionNavigation")]
    public virtual ICollection<ComOrdenescompra> ComOrdenescompras { get; set; } = new List<ComOrdenescompra>();

    [InverseProperty("UsuariocreacionNavigation")]
    public virtual ICollection<InvMovimiento> InvMovimientos { get; set; } = new List<InvMovimiento>();

    [InverseProperty("Usuario")]
    public virtual ICollection<InvProductosHistorico> InvProductosHistoricos { get; set; } = new List<InvProductosHistorico>();

    [InverseProperty("UsuariocreacionNavigation")]
    public virtual ICollection<PrvProveedore> PrvProveedores { get; set; } = new List<PrvProveedore>();

    [InverseProperty("Usuario")]
    public virtual ICollection<RrhEmpleado> RrhEmpleados { get; set; } = new List<RrhEmpleado>();

    [InverseProperty("Usuario")]
    public virtual ICollection<SecSesione> SecSesiones { get; set; } = new List<SecSesione>();

    [InverseProperty("Usuario")]
    public virtual ICollection<SecUsuariorole> SecUsuarioroles { get; set; } = new List<SecUsuariorole>();

    [InverseProperty("UsuariocreacionNavigation")]
    public virtual ICollection<VenCotizacione> VenCotizaciones { get; set; } = new List<VenCotizacione>();

    [InverseProperty("UsuariocreacionNavigation")]
    public virtual ICollection<VenFactura> VenFacturas { get; set; } = new List<VenFactura>();

    [InverseProperty("UsuariocreacionNavigation")]
    public virtual ICollection<VenNotascredito> VenNotascreditos { get; set; } = new List<VenNotascredito>();

    [InverseProperty("UsuariocreacionNavigation")]
    public virtual ICollection<VenPedido> VenPedidos { get; set; } = new List<VenPedido>();
}