// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DepositoDental.Models.Entities;

[Table("sec_usuarioroles")]
[Index("Usuarioid", "Rolid", Name = "UK_sec_usuarioroles", IsUnique = true)]
public partial class SecUsuariorole
{
    [Key]
    [Column("usuariorolid")]
    public long Usuariorolid { get; set; }

    [Column("usuarioid")]
    public long Usuarioid { get; set; }

    [Column("rolid")]
    public long Rolid { get; set; }

    [Column("activo")]
    public bool? Activo { get; set; }

    [ForeignKey("Rolid")]
    [InverseProperty("SecUsuarioroles")]
    public virtual SecRole Rol { get; set; }

    [ForeignKey("Usuarioid")]
    [InverseProperty("SecUsuarioroles")]
    public virtual SecUsuario Usuario { get; set; }
}