// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DepositoDental.Models.Entities;

[Table("ven_condicionespago")]
[Index("Nombrecondicion", Name = "UQ__ven_cond__61764BC374F8E5C2", IsUnique = true)]
public partial class VenCondicionespago
{
    [Key]
    [Column("condicionpagoid")]
    public long Condicionpagoid { get; set; }

    [Required]
    [Column("nombrecondicion")]
    [StringLength(255)]
    public string Nombrecondicion { get; set; }

    [Column("dias")]
    public int Dias { get; set; }

    [InverseProperty("Condicionpago")]
    public virtual ICollection<VenFactura> VenFacturas { get; set; } = new List<VenFactura>();
}