// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DepositoDental.Models.Entities;

[Table("ven_cotizaciones")]
[Index("Clienteid", Name = "IX_ven_cotizaciones_cliente")]
[Index("Fechacotizacion", Name = "IX_ven_cotizaciones_fecha")]
[Index("Numerocotizacion", Name = "UQ__ven_coti__6E21F706EC588429", IsUnique = true)]
public partial class VenCotizacione
{
    [Key]
    [Column("cotizacionid")]
    public long Cotizacionid { get; set; }

    [Required]
    [Column("numerocotizacion")]
    [StringLength(50)]
    public string Numerocotizacion { get; set; }

    [Column("clienteid")]
    public long Clienteid { get; set; }

    [Column("fechacotizacion")]
    public DateOnly Fechacotizacion { get; set; }

    [Column("total", TypeName = "decimal(15, 2)")]
    public decimal? Total { get; set; }

    [Column("estadoid")]
    public long Estadoid { get; set; }

    [Column("usuariocreacion")]
    public long Usuariocreacion { get; set; }

    [ForeignKey("Clienteid")]
    [InverseProperty("VenCotizaciones")]
    public virtual CliCliente Cliente { get; set; }

    [ForeignKey("Estadoid")]
    [InverseProperty("VenCotizaciones")]
    public virtual CatEstado Estado { get; set; }

    [ForeignKey("Usuariocreacion")]
    [InverseProperty("VenCotizaciones")]
    public virtual SecUsuario UsuariocreacionNavigation { get; set; }

    [InverseProperty("Cotizacion")]
    public virtual ICollection<VenCotizacionesdetalle> VenCotizacionesdetalles { get; set; } = new List<VenCotizacionesdetalle>();
}