// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DepositoDental.Models.Entities;

[Table("ven_cotizacionesdetalles")]
public partial class VenCotizacionesdetalle
{
    [Key]
    [Column("cotizaciondetalleid")]
    public long Cotizaciondetalleid { get; set; }

    [Column("cotizacionid")]
    public long Cotizacionid { get; set; }

    [Column("productoid")]
    public long Productoid { get; set; }

    [Column("cantidad")]
    public int Cantidad { get; set; }

    [Column("preciounitario", TypeName = "decimal(15, 4)")]
    public decimal Preciounitario { get; set; }

    [Column("descuentoporcentaje", TypeName = "decimal(5, 2)")]
    public decimal? Descuentoporcentaje { get; set; }

    [ForeignKey("Cotizacionid")]
    [InverseProperty("VenCotizacionesdetalles")]
    public virtual VenCotizacione Cotizacion { get; set; }

    [ForeignKey("Productoid")]
    [InverseProperty("VenCotizacionesdetalles")]
    public virtual InvProducto Producto { get; set; }
}