// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DepositoDental.Models.Entities;

[Table("ven_facturas")]
[Index("Clienteid", Name = "IX_ven_facturas_cliente")]
[Index("Fechafactura", Name = "IX_ven_facturas_fecha")]
[Index("Fechafactura", "Estadoid", Name = "IX_ven_facturas_fecha_estado")]
[Index("Serieid", Name = "IX_ven_facturas_serie")]
[Index("Serieid", "Numerofactura", Name = "UK_ven_facturas", IsUnique = true)]
[Index("Codigogeneracion", Name = "UQ__ven_fact__4B9DBAFEFE1667F9", IsUnique = true)]
public partial class VenFactura
{
    [Key]
    [Column("facturaid")]
    public long Facturaid { get; set; }

    [Required]
    [Column("numerofactura")]
    [StringLength(50)]
    public string Numerofactura { get; set; }

    [Column("serieid")]
    public long Serieid { get; set; }

    [Column("tipodocumentoid")]
    public long Tipodocumentoid { get; set; }

    [Column("clienteid")]
    public long Clienteid { get; set; }

    [Column("fechafactura")]
    public DateOnly Fechafactura { get; set; }

    [Column("fechavencimiento")]
    public DateOnly? Fechavencimiento { get; set; }

    [Required]
    [Column("nombrecliente")]
    [StringLength(255)]
    public string Nombrecliente { get; set; }

    [Column("duicliente")]
    [StringLength(15)]
    public string Duicliente { get; set; }

    [Column("nitcliente")]
    [StringLength(20)]
    public string Nitcliente { get; set; }

    [Column("nrccliente")]
    [StringLength(20)]
    public string Nrccliente { get; set; }

    [Column("direccioncliente")]
    public string Direccioncliente { get; set; }

    [Column("subtotal", TypeName = "decimal(15, 2)")]
    public decimal? Subtotal { get; set; }

    [Column("descuento", TypeName = "decimal(15, 2)")]
    public decimal? Descuento { get; set; }

    [Column("iva", TypeName = "decimal(15, 2)")]
    public decimal? Iva { get; set; }

    [Column("total", TypeName = "decimal(15, 2)")]
    public decimal? Total { get; set; }

    [Column("condicionpagoid")]
    public long? Condicionpagoid { get; set; }

    [Column("codigogeneracion")]
    [StringLength(100)]
    public string Codigogeneracion { get; set; }

    [Column("numerocontrol")]
    [StringLength(100)]
    public string Numerocontrol { get; set; }

    [Column("sellorecepcion")]
    [StringLength(255)]
    public string Sellorecepcion { get; set; }

    [Column("fecharecepcionmh")]
    public DateTime? Fecharecepcionmh { get; set; }

    [Column("estadomh")]
    [StringLength(50)]
    public string Estadomh { get; set; }

    [Column("observacionesmh")]
    public string Observacionesmh { get; set; }

    [Column("estadoid")]
    public long Estadoid { get; set; }

    [Column("anulada")]
    public bool? Anulada { get; set; }

    [Column("usuariocreacion")]
    public long Usuariocreacion { get; set; }

    [ForeignKey("Clienteid")]
    [InverseProperty("VenFacturas")]
    public virtual CliCliente Cliente { get; set; }

    [ForeignKey("Condicionpagoid")]
    [InverseProperty("VenFacturas")]
    public virtual VenCondicionespago Condicionpago { get; set; }

    [ForeignKey("Estadoid")]
    [InverseProperty("VenFacturas")]
    public virtual CatEstado Estado { get; set; }

    [ForeignKey("Serieid")]
    [InverseProperty("VenFacturas")]
    public virtual VenSeries Serie { get; set; }

    [ForeignKey("Usuariocreacion")]
    [InverseProperty("VenFacturas")]
    public virtual SecUsuario UsuariocreacionNavigation { get; set; }

    [InverseProperty("Factura")]
    public virtual ICollection<VenFacturasdetalle> VenFacturasdetalles { get; set; } = new List<VenFacturasdetalle>();

    [InverseProperty("Factura")]
    public virtual ICollection<VenNotascredito> VenNotascreditos { get; set; } = new List<VenNotascredito>();
}