// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DepositoDental.Models.Entities;

[Table("ven_facturasdetalles")]
[Index("Facturaid", Name = "IX_ven_facturasdetalles_factura")]
[Index("Productoid", Name = "IX_ven_facturasdetalles_producto")]
public partial class VenFacturasdetalle
{
    [Key]
    [Column("facturadetalleid")]
    public long Facturadetalleid { get; set; }

    [Column("facturaid")]
    public long Facturaid { get; set; }

    [Column("productoid")]
    public long Productoid { get; set; }

    [Required]
    [Column("codigoproducto")]
    [StringLength(50)]
    public string Codigoproducto { get; set; }

    [Required]
    [Column("nombreproducto")]
    [StringLength(255)]
    public string Nombreproducto { get; set; }

    [Column("cantidad")]
    public int Cantidad { get; set; }

    [Column("preciounitario", TypeName = "decimal(15, 4)")]
    public decimal Preciounitario { get; set; }

    [Column("ventasafectas", TypeName = "decimal(15, 2)")]
    public decimal Ventasafectas { get; set; }

    [Column("iva", TypeName = "decimal(15, 2)")]
    public decimal? Iva { get; set; }

    [Column("total_linea", TypeName = "decimal(15, 2)")]
    public decimal TotalLinea { get; set; }

    [ForeignKey("Facturaid")]
    [InverseProperty("VenFacturasdetalles")]
    public virtual VenFactura Factura { get; set; }

    [ForeignKey("Productoid")]
    [InverseProperty("VenFacturasdetalles")]
    public virtual InvProducto Producto { get; set; }
}