// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DepositoDental.Models.Entities;

[Table("ven_notascredito")]
[Index("Numeronota", Name = "UQ__ven_nota__47A71A94ABA033A6", IsUnique = true)]
[Index("Codigogeneracion", Name = "UQ__ven_nota__4B9DBAFEC7A17B86", IsUnique = true)]
public partial class VenNotascredito
{
    [Key]
    [Column("notacreditoid")]
    public long Notacreditoid { get; set; }

    [Required]
    [Column("numeronota")]
    [StringLength(50)]
    public string Numeronota { get; set; }

    [Column("serieid")]
    public long Serieid { get; set; }

    [Column("facturaid")]
    public long Facturaid { get; set; }

    [Column("fechanota")]
    public DateOnly Fechanota { get; set; }

    [Required]
    [Column("motivonota")]
    public string Motivonota { get; set; }

    [Column("total", TypeName = "decimal(15, 2)")]
    public decimal? Total { get; set; }

    [Column("codigogeneracion")]
    [StringLength(100)]
    public string Codigogeneracion { get; set; }

    [Column("usuariocreacion")]
    public long Usuariocreacion { get; set; }

    [ForeignKey("Facturaid")]
    [InverseProperty("VenNotascreditos")]
    public virtual VenFactura Factura { get; set; }

    [ForeignKey("Serieid")]
    [InverseProperty("VenNotascreditos")]
    public virtual VenSeries Serie { get; set; }

    [ForeignKey("Usuariocreacion")]
    [InverseProperty("VenNotascreditos")]
    public virtual SecUsuario UsuariocreacionNavigation { get; set; }
}