// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DepositoDental.Models.Entities;

[Table("ven_pedidos")]
[Index("Clienteid", Name = "IX_ven_pedidos_cliente")]
[Index("Fechapedido", Name = "IX_ven_pedidos_fecha")]
[Index("Numeropedido", Name = "UQ__ven_pedi__B896FF8F16475BBF", IsUnique = true)]
public partial class VenPedido
{
    [Key]
    [Column("pedidoid")]
    public long Pedidoid { get; set; }

    [Required]
    [Column("numeropedido")]
    [StringLength(50)]
    public string Numeropedido { get; set; }

    [Column("clienteid")]
    public long Clienteid { get; set; }

    [Column("fechapedido")]
    public DateOnly Fechapedido { get; set; }

    [Column("total", TypeName = "decimal(15, 2)")]
    public decimal? Total { get; set; }

    [Column("estadoid")]
    public long Estadoid { get; set; }

    [Column("usuariocreacion")]
    public long Usuariocreacion { get; set; }

    [ForeignKey("Clienteid")]
    [InverseProperty("VenPedidos")]
    public virtual CliCliente Cliente { get; set; }

    [ForeignKey("Estadoid")]
    [InverseProperty("VenPedidos")]
    public virtual CatEstado Estado { get; set; }

    [ForeignKey("Usuariocreacion")]
    [InverseProperty("VenPedidos")]
    public virtual SecUsuario UsuariocreacionNavigation { get; set; }

    [InverseProperty("Pedido")]
    public virtual ICollection<VenPedidosdetalle> VenPedidosdetalles { get; set; } = new List<VenPedidosdetalle>();
}