// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DepositoDental.Models.Entities;

[Table("ven_pedidosdetalle")]
public partial class VenPedidosdetalle
{
    [Key]
    [Column("pedidodetalleid")]
    public long Pedidodetalleid { get; set; }

    [Column("pedidoid")]
    public long Pedidoid { get; set; }

    [Column("productoid")]
    public long Productoid { get; set; }

    [Column("cantidad")]
    public int Cantidad { get; set; }

    [Column("preciounitario", TypeName = "decimal(15, 4)")]
    public decimal Preciounitario { get; set; }

    [ForeignKey("Pedidoid")]
    [InverseProperty("VenPedidosdetalles")]
    public virtual VenPedido Pedido { get; set; }

    [ForeignKey("Productoid")]
    [InverseProperty("VenPedidosdetalles")]
    public virtual InvProducto Producto { get; set; }
}