// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DepositoDental.Models.Entities;

[Table("ven_series")]
[Index("Tipodocumentoid", "Serie", Name = "UK_ven_series", IsUnique = true)]
public partial class VenSeries
{
    [Key]
    [Column("serieid")]
    public long Serieid { get; set; }

    [Column("tipodocumentoid")]
    public long Tipodocumentoid { get; set; }

    [Required]
    [Column("serie")]
    [StringLength(50)]
    public string Serie { get; set; }

    [Column("numeroactual")]
    public long Numeroactual { get; set; }

    [Column("numerofinal")]
    public long Numerofinal { get; set; }

    [Column("activo")]
    public bool? Activo { get; set; }

    [InverseProperty("Serie")]
    public virtual ICollection<VenFactura> VenFacturas { get; set; } = new List<VenFactura>();

    [InverseProperty("Serie")]
    public virtual ICollection<VenNotascredito> VenNotascreditos { get; set; } = new List<VenNotascredito>();
}