// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DepositoDental.Models.Entities;

[Keyless]
public partial class VwAnalisisVentasPorVendedor
{
    [Column("vendedorid")]
    public long Vendedorid { get; set; }

    [Required]
    [Column("vendedor")]
    [StringLength(255)]
    public string Vendedor { get; set; }

    [Column("anio")]
    public int? Anio { get; set; }

    [Column("mes")]
    public int? Mes { get; set; }

    [Column("numerofacturas")]
    public int? Numerofacturas { get; set; }

    [Column("totalvendido", TypeName = "decimal(38, 2)")]
    public decimal? Totalvendido { get; set; }

    [Column("ventapromedio", TypeName = "decimal(38, 6)")]
    public decimal? Ventapromedio { get; set; }
}