// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DepositoDental.Models.Entities;

[Keyless]
public partial class VwAsientosContablesResuman
{
    [Column("asientoid")]
    public long Asientoid { get; set; }

    [Required]
    [Column("numeroasiento")]
    [StringLength(50)]
    public string Numeroasiento { get; set; }

    [Column("fechaasiento")]
    public DateOnly Fechaasiento { get; set; }

    [Required]
    [Column("concepto")]
    public string Concepto { get; set; }

    [Column("totaldebe", TypeName = "decimal(15, 2)")]
    public decimal? Totaldebe { get; set; }

    [Column("totalhaber", TypeName = "decimal(15, 2)")]
    public decimal? Totalhaber { get; set; }

    [Column("anio")]
    public int Anio { get; set; }

    [Column("mes")]
    public int Mes { get; set; }

    [Required]
    [Column("estado")]
    [StringLength(255)]
    public string Estado { get; set; }
}