// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DepositoDental.Models.Entities;

[Keyless]
public partial class VwClientesCompleto
{
    [Column("clienteid")]
    public long Clienteid { get; set; }

    [Required]
    [Column("codigocliente")]
    [StringLength(50)]
    public string Codigocliente { get; set; }

    [Required]
    [Column("tipocliente")]
    [StringLength(255)]
    public string Tipocliente { get; set; }

    [Required]
    [Column("razonsocial")]
    [StringLength(255)]
    public string Razonsocial { get; set; }

    [Column("nombrecomercial")]
    [StringLength(255)]
    public string Nombrecomercial { get; set; }

    [Column("dui")]
    [StringLength(15)]
    public string Dui { get; set; }

    [Column("nit")]
    [StringLength(20)]
    public string Nit { get; set; }

    [Column("nrc")]
    [StringLength(20)]
    public string Nrc { get; set; }

    [Column("escontribuyente")]
    public bool? Escontribuyente { get; set; }

    [Column("giro")]
    [StringLength(255)]
    public string Giro { get; set; }

    [Column("correoelectronico")]
    [StringLength(255)]
    public string Correoelectronico { get; set; }

    [Column("telefono1")]
    [StringLength(20)]
    public string Telefono1 { get; set; }

    [Column("whatsapp")]
    [StringLength(20)]
    public string Whatsapp { get; set; }

    [Column("direccion")]
    public string Direccion { get; set; }

    [Column("nombremunicipio")]
    [StringLength(255)]
    public string Nombremunicipio { get; set; }

    [Column("nombredepartamento")]
    [StringLength(255)]
    public string Nombredepartamento { get; set; }

    [Column("nombrepais")]
    [StringLength(255)]
    public string Nombrepais { get; set; }

    [Column("municipioid")]
    public long? Municipioid { get; set; }

    [Column("departamentoid")]
    public long? Departamentoid { get; set; }

    [Column("paisid")]
    public long? Paisid { get; set; }

    [Column("creditolimitado", TypeName = "decimal(15, 2)")]
    public decimal? Creditolimitado { get; set; }

    [Column("diasplazocredito")]
    public int? Diasplazocredito { get; set; }

    [Column("activo")]
    public bool? Activo { get; set; }

    [Column("usuariocreacion")]
    public long? Usuariocreacion { get; set; }

    [Column("nombreusuariocreacion")]
    [StringLength(255)]
    public string Nombreusuariocreacion { get; set; }

    [Column("fechacreacion")]
    public DateTime? Fechacreacion { get; set; }
}