// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DepositoDental.Models.Entities;

[Keyless]
public partial class VwControlLotesVencimiento
{
    [Column("loteid")]
    public long Loteid { get; set; }

    [Required]
    [Column("numerolote")]
    [StringLength(50)]
    public string Numerolote { get; set; }

    [Column("fechavencimiento")]
    public DateOnly? Fechavencimiento { get; set; }

    [Column("diasparavencer")]
    public int? Diasparavencer { get; set; }

    [Column("stocklote")]
    public int? Stocklote { get; set; }

    [Column("productoid")]
    public long Productoid { get; set; }

    [Required]
    [Column("nombreproducto")]
    [StringLength(255)]
    public string Nombreproducto { get; set; }

    [Required]
    [Column("codigoproducto")]
    [StringLength(50)]
    public string Codigoproducto { get; set; }
}