// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DepositoDental.Models.Entities;

[Keyless]
public partial class VwEmpleadosActivo
{
    [Column("empleadoid")]
    public long Empleadoid { get; set; }

    [Required]
    [Column("codigoempleado")]
    [StringLength(50)]
    public string Codigoempleado { get; set; }

    [Required]
    [Column("primernombre")]
    [StringLength(100)]
    public string Primernombre { get; set; }

    [Column("segundonombre")]
    [StringLength(100)]
    public string Segundonombre { get; set; }

    [Required]
    [Column("primerapellido")]
    [StringLength(100)]
    public string Primerapellido { get; set; }

    [Column("segundoapellido")]
    [StringLength(100)]
    public string Segundoapellido { get; set; }

    [Required]
    [Column("nombrecompleto")]
    [StringLength(201)]
    public string Nombrecompleto { get; set; }

    [Column("dui")]
    [StringLength(15)]
    public string Dui { get; set; }

    [Column("nit")]
    [StringLength(20)]
    public string Nit { get; set; }

    [Column("fechanacimiento")]
    public DateOnly? Fechanacimiento { get; set; }

    [Column("telefono")]
    [StringLength(20)]
    public string Telefono { get; set; }

    [Column("correopersonal")]
    [StringLength(255)]
    public string Correopersonal { get; set; }

    [Column("cargoid")]
    public long? Cargoid { get; set; }

    [Column("nombrecargo")]
    [StringLength(255)]
    public string Nombrecargo { get; set; }

    [Column("fechaingreso")]
    public DateOnly Fechaingreso { get; set; }

    [Column("salariobase", TypeName = "decimal(10, 2)")]
    public decimal Salariobase { get; set; }

    [Column("usuarioasociado")]
    public long? Usuarioasociado { get; set; }

    [Column("nombreusuario")]
    [StringLength(255)]
    public string Nombreusuario { get; set; }
}