// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DepositoDental.Models.Entities;

[Keyless]
public partial class VwFacturasResuman
{
    [Column("facturaid")]
    public long Facturaid { get; set; }

    [Required]
    [Column("numerofactura")]
    [StringLength(50)]
    public string Numerofactura { get; set; }

    [Required]
    [Column("serie")]
    [StringLength(50)]
    public string Serie { get; set; }

    [Required]
    [Column("tipodocumento")]
    [StringLength(255)]
    public string Tipodocumento { get; set; }

    [Column("clienteid")]
    public long Clienteid { get; set; }

    [Required]
    [Column("cliente")]
    [StringLength(255)]
    public string Cliente { get; set; }

    [Column("fechafactura")]
    public DateOnly Fechafactura { get; set; }

    [Column("fechavencimiento")]
    public DateOnly? Fechavencimiento { get; set; }

    [Column("subtotal", TypeName = "decimal(15, 2)")]
    public decimal? Subtotal { get; set; }

    [Column("descuento", TypeName = "decimal(15, 2)")]
    public decimal? Descuento { get; set; }

    [Column("iva", TypeName = "decimal(15, 2)")]
    public decimal? Iva { get; set; }

    [Column("total", TypeName = "decimal(15, 2)")]
    public decimal? Total { get; set; }

    [Column("condicionpago")]
    [StringLength(255)]
    public string Condicionpago { get; set; }

    [Required]
    [Column("estado")]
    [StringLength(255)]
    public string Estado { get; set; }

    [Column("estadocolor")]
    [StringLength(7)]
    public string Estadocolor { get; set; }

    [Column("anulada")]
    public bool? Anulada { get; set; }

    [Column("usuariocreacion")]
    public long Usuariocreacion { get; set; }

    [Required]
    [Column("vendedor")]
    [StringLength(255)]
    public string Vendedor { get; set; }
}