// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DepositoDental.Models.Entities;

[Keyless]
public partial class VwMovimientosInventario
{
    [Column("movimientoid")]
    public long Movimientoid { get; set; }

    [Required]
    [Column("numeromovimiento")]
    [StringLength(50)]
    public string Numeromovimiento { get; set; }

    [Required]
    [Column("tipomovimiento")]
    [StringLength(255)]
    public string Tipomovimiento { get; set; }

    [Required]
    [Column("tipooperacion")]
    [StringLength(1)]
    [Unicode(false)]
    public string Tipooperacion { get; set; }

    [Column("fechamovimiento")]
    public DateTime? Fechamovimiento { get; set; }

    [Column("bodegaorigen")]
    [StringLength(255)]
    public string Bodegaorigen { get; set; }

    [Column("bodegadestino")]
    [StringLength(255)]
    public string Bodegadestino { get; set; }

    [Column("observaciones")]
    public string Observaciones { get; set; }

    [Required]
    [Column("estado")]
    [StringLength(255)]
    public string Estado { get; set; }

    [Required]
    [Column("usuario_creacion")]
    [StringLength(201)]
    public string UsuarioCreacion { get; set; }
}