// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DepositoDental.Models.Entities;

[Keyless]
public partial class VwNotasCreditoResuman
{
    [Column("notacreditoid")]
    public long Notacreditoid { get; set; }

    [Required]
    [Column("numeronota")]
    [StringLength(50)]
    public string Numeronota { get; set; }

    [Column("fechanota")]
    public DateOnly Fechanota { get; set; }

    [Required]
    [Column("motivonota")]
    public string Motivonota { get; set; }

    [Column("total", TypeName = "decimal(15, 2)")]
    public decimal? Total { get; set; }

    [Column("facturarelacionadaid")]
    public long Facturarelacionadaid { get; set; }

    [Required]
    [Column("facturarelacionada")]
    [StringLength(50)]
    public string Facturarelacionada { get; set; }

    [Required]
    [Column("serie")]
    [StringLength(50)]
    public string Serie { get; set; }

    [Required]
    [Column("creadopor")]
    [StringLength(255)]
    public string Creadopor { get; set; }
}