// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DepositoDental.Models.Entities;

[Keyless]
public partial class VwOrdenesCompraResuman
{
    [Column("ordencompraid")]
    public long Ordencompraid { get; set; }

    [Required]
    [Column("numeroorden")]
    [StringLength(50)]
    public string Numeroorden { get; set; }

    [Column("fechaorden")]
    public DateOnly Fechaorden { get; set; }

    [Column("proveedorid")]
    public long Proveedorid { get; set; }

    [Required]
    [Column("proveedor")]
    [StringLength(255)]
    public string Proveedor { get; set; }

    [Column("total", TypeName = "decimal(15, 2)")]
    public decimal? Total { get; set; }

    [Required]
    [Column("estado")]
    [StringLength(255)]
    public string Estado { get; set; }

    [Column("estadocolor")]
    [StringLength(7)]
    public string Estadocolor { get; set; }

    [Required]
    [Column("creadopor")]
    [StringLength(255)]
    public string Creadopor { get; set; }
}