// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DepositoDental.Models.Entities;

[Keyless]
public partial class VwPedidosResuman
{
    [Column("pedidoid")]
    public long Pedidoid { get; set; }

    [Required]
    [Column("numeropedido")]
    [StringLength(50)]
    public string Numeropedido { get; set; }

    [Column("fechapedido")]
    public DateOnly Fechapedido { get; set; }

    [Column("clienteid")]
    public long Clienteid { get; set; }

    [Required]
    [Column("cliente")]
    [StringLength(255)]
    public string Cliente { get; set; }

    [Column("total", TypeName = "decimal(15, 2)")]
    public decimal? Total { get; set; }

    [Required]
    [Column("estado")]
    [StringLength(255)]
    public string Estado { get; set; }

    [Column("estadocolor")]
    [StringLength(7)]
    public string Estadocolor { get; set; }

    [Required]
    [Column("creadopor")]
    [StringLength(255)]
    public string Creadopor { get; set; }
}