// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DepositoDental.Models.Entities;

[Keyless]
public partial class VwProductosCompleto
{
    [Column("productoid")]
    public long Productoid { get; set; }

    [Required]
    [Column("codigoproducto")]
    [StringLength(50)]
    public string Codigoproducto { get; set; }

    [Column("codigobarras")]
    [StringLength(50)]
    public string Codigobarras { get; set; }

    [Required]
    [Column("nombreproducto")]
    [StringLength(255)]
    public string Nombreproducto { get; set; }

    [Column("descripcion")]
    public string Descripcion { get; set; }

    [Required]
    [Column("nombrecategoria")]
    [StringLength(255)]
    public string Nombrecategoria { get; set; }

    [Column("nombremarca")]
    [StringLength(255)]
    public string Nombremarca { get; set; }

    [Required]
    [Column("nombreunidad")]
    [StringLength(100)]
    public string Nombreunidad { get; set; }

    [Column("categoriaid")]
    public long Categoriaid { get; set; }

    [Column("marcaid")]
    public long? Marcaid { get; set; }

    [Column("unidadmedidaid")]
    public long Unidadmedidaid { get; set; }

    [Column("costopromedio", TypeName = "decimal(15, 4)")]
    public decimal? Costopromedio { get; set; }

    [Column("precioventa1", TypeName = "decimal(15, 4)")]
    public decimal? Precioventa1 { get; set; }

    [Column("precioventa2", TypeName = "decimal(15, 4)")]
    public decimal? Precioventa2 { get; set; }

    [Column("precioventa3", TypeName = "decimal(15, 4)")]
    public decimal? Precioventa3 { get; set; }

    [Column("stockminimo")]
    public int? Stockminimo { get; set; }

    [Column("stockmaximo")]
    public int? Stockmaximo { get; set; }

    [Column("stockactual")]
    public int? Stockactual { get; set; }

    [Column("stockcomprometido")]
    public int? Stockcomprometido { get; set; }

    [Column("stockdisponible")]
    public int? Stockdisponible { get; set; }

    [Column("aplicaiva")]
    public bool? Aplicaiva { get; set; }

    [Column("porcentajeiva", TypeName = "decimal(5, 2)")]
    public decimal? Porcentajeiva { get; set; }

    [Column("codigotributario")]
    [StringLength(50)]
    public string Codigotributario { get; set; }

    [Column("manejavencimiento")]
    public bool? Manejavencimiento { get; set; }

    [Column("manejalotes")]
    public bool? Manejalotes { get; set; }

    [Column("activo")]
    public bool? Activo { get; set; }

    [Column("esservicio")]
    public bool? Esservicio { get; set; }
}