// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DepositoDental.Models.Entities;

[Keyless]
public partial class VwReporteVentasVendedor
{
    [Column("usuarioid")]
    public long Usuarioid { get; set; }

    [Required]
    [Column("vendedor")]
    [StringLength(201)]
    public string Vendedor { get; set; }

    [Column("anio")]
    public int? Anio { get; set; }

    [Column("mes")]
    public int? Mes { get; set; }

    [Column("fechames")]
    public DateOnly? Fechames { get; set; }

    [Column("cantidad_facturas")]
    public int? CantidadFacturas { get; set; }

    [Column("total_ventas", TypeName = "decimal(38, 2)")]
    public decimal? TotalVentas { get; set; }

    [Column("promedio_por_factura", TypeName = "decimal(38, 6)")]
    public decimal? PromedioPorFactura { get; set; }

    [Column("ventas_ultimos_30dias", TypeName = "decimal(38, 2)")]
    public decimal? VentasUltimos30dias { get; set; }

    [Column("clientes_asignados")]
    public int? ClientesAsignados { get; set; }
}