// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DepositoDental.Models.Entities;

[Keyless]
public partial class VwReporteInventarioDetallado
{
    [Column("productoid")]
    public long Productoid { get; set; }

    [Required]
    [Column("codigoproducto")]
    [StringLength(50)]
    public string Codigoproducto { get; set; }

    [Required]
    [Column("nombreproducto")]
    [StringLength(255)]
    public string Nombreproducto { get; set; }

    [Column("costopromedio", TypeName = "decimal(15, 4)")]
    public decimal? Costopromedio { get; set; }

    [Column("precioventa1", TypeName = "decimal(15, 4)")]
    public decimal? Precioventa1 { get; set; }

    [Column("stocktotal")]
    public int? Stocktotal { get; set; }

    [Column("bodegaid")]
    public long? Bodegaid { get; set; }

    [Column("nombrebodega")]
    [StringLength(255)]
    public string Nombrebodega { get; set; }

    [Column("ubicacionid")]
    public long? Ubicacionid { get; set; }

    [Column("nombreubicacion")]
    [StringLength(255)]
    public string Nombreubicacion { get; set; }

    [Column("stockenbodega")]
    public int? Stockenbodega { get; set; }

    [Column("costoinventariobodega", TypeName = "decimal(26, 4)")]
    public decimal? Costoinventariobodega { get; set; }

    [Required]
    [Column("estadostock")]
    [StringLength(10)]
    [Unicode(false)]
    public string Estadostock { get; set; }
}