// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DepositoDental.Models.Entities;

[Keyless]
public partial class VwReporteInventario
{
    [Column("productoid")]
    public long Productoid { get; set; }

    [Required]
    [Column("codigoproducto")]
    [StringLength(50)]
    public string Codigoproducto { get; set; }

    [Required]
    [Column("nombreproducto")]
    [StringLength(255)]
    public string Nombreproducto { get; set; }

    [Required]
    [Column("nombrecategoria")]
    [StringLength(255)]
    public string Nombrecategoria { get; set; }

    [Column("nombremarca")]
    [StringLength(255)]
    public string Nombremarca { get; set; }

    [Required]
    [Column("nombreunidad")]
    [StringLength(100)]
    public string Nombreunidad { get; set; }

    [Column("costopromedio", TypeName = "decimal(15, 4)")]
    public decimal? Costopromedio { get; set; }

    [Column("precioventa1", TypeName = "decimal(15, 4)")]
    public decimal? Precioventa1 { get; set; }

    [Column("stockactual")]
    public int? Stockactual { get; set; }

    [Column("stockminimo")]
    public int? Stockminimo { get; set; }

    [Column("stockmaximo")]
    public int? Stockmaximo { get; set; }

    [Required]
    [Column("estadoinventario")]
    [StringLength(7)]
    [Unicode(false)]
    public string Estadoinventario { get; set; }

    [Column("diferencia_minimo")]
    public int? DiferenciaMinimo { get; set; }

    [Column("diferencia_maximo")]
    public int? DiferenciaMaximo { get; set; }

    [Column("nombrebodega")]
    [StringLength(255)]
    public string Nombrebodega { get; set; }

    [Column("stockbodega")]
    public int? Stockbodega { get; set; }

    [Column("nombreubicacion")]
    [StringLength(255)]
    public string Nombreubicacion { get; set; }
}