// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DepositoDental.Models.Entities;

[Keyless]
public partial class VwReporteFacturacion
{
    [Column("facturaid")]
    public long Facturaid { get; set; }

    [Required]
    [Column("numerofactura")]
    [StringLength(50)]
    public string Numerofactura { get; set; }

    [Column("serieid")]
    public long Serieid { get; set; }

    [Required]
    [Column("serie")]
    [StringLength(50)]
    public string Serie { get; set; }

    [Column("fechafactura")]
    public DateOnly Fechafactura { get; set; }

    [Column("fechavencimiento")]
    public DateOnly? Fechavencimiento { get; set; }

    [Column("clienteid")]
    public long Clienteid { get; set; }

    [Required]
    [Column("nombrecliente")]
    [StringLength(255)]
    public string Nombrecliente { get; set; }

    [Column("nitcliente")]
    [StringLength(20)]
    public string Nitcliente { get; set; }

    [Column("nrccliente")]
    [StringLength(20)]
    public string Nrccliente { get; set; }

    [Column("productoid")]
    public long Productoid { get; set; }

    [Required]
    [Column("codigoproducto")]
    [StringLength(50)]
    public string Codigoproducto { get; set; }

    [Required]
    [Column("nombreproducto")]
    [StringLength(255)]
    public string Nombreproducto { get; set; }

    [Column("cantidad")]
    public int Cantidad { get; set; }

    [Column("preciounitario", TypeName = "decimal(15, 4)")]
    public decimal Preciounitario { get; set; }

    [Column("ventasafectas", TypeName = "decimal(15, 2)")]
    public decimal Ventasafectas { get; set; }

    [Column("iva", TypeName = "decimal(15, 2)")]
    public decimal? Iva { get; set; }

    [Column("totaldetalle", TypeName = "decimal(15, 2)")]
    public decimal Totaldetalle { get; set; }

    [Column("subtotal", TypeName = "decimal(15, 2)")]
    public decimal? Subtotal { get; set; }

    [Column("descuento", TypeName = "decimal(15, 2)")]
    public decimal? Descuento { get; set; }

    [Column("ivatotal", TypeName = "decimal(15, 2)")]
    public decimal? Ivatotal { get; set; }

    [Column("total", TypeName = "decimal(15, 2)")]
    public decimal? Total { get; set; }

    [Required]
    [Column("nombreestado")]
    [StringLength(255)]
    public string Nombreestado { get; set; }

    [Required]
    [Column("vendedor")]
    [StringLength(201)]
    public string Vendedor { get; set; }

    [Column("condicionpago")]
    [StringLength(255)]
    public string Condicionpago { get; set; }

    [Column("diasvencidos")]
    public int? Diasvencidos { get; set; }
}