// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DepositoDental.Models.Entities;

[Keyless]
public partial class VwReporteFacturacionDetallado
{
    [Column("facturaid")]
    public long Facturaid { get; set; }

    [Required]
    [Column("numerofactura")]
    [StringLength(50)]
    public string Numerofactura { get; set; }

    [Required]
    [Column("serie")]
    [StringLength(50)]
    public string Serie { get; set; }

    [Column("fechafactura")]
    public DateOnly Fechafactura { get; set; }

    [Column("fechavencimiento")]
    public DateOnly? Fechavencimiento { get; set; }

    [Column("totalfactura", TypeName = "decimal(15, 2)")]
    public decimal? Totalfactura { get; set; }

    [Required]
    [Column("estadofactura")]
    [StringLength(255)]
    public string Estadofactura { get; set; }

    [Column("anulada")]
    public bool? Anulada { get; set; }

    [Column("clienteid")]
    public long Clienteid { get; set; }

    [Required]
    [Column("nombrecliente")]
    [StringLength(255)]
    public string Nombrecliente { get; set; }

    [Column("nitcliente")]
    [StringLength(20)]
    public string Nitcliente { get; set; }

    [Column("nrccliente")]
    [StringLength(20)]
    public string Nrccliente { get; set; }

    [Column("vendedorid")]
    public long Vendedorid { get; set; }

    [Required]
    [Column("vendedor")]
    [StringLength(255)]
    public string Vendedor { get; set; }

    [Column("facturadetalleid")]
    public long Facturadetalleid { get; set; }

    [Column("productoid")]
    public long Productoid { get; set; }

    [Required]
    [Column("codigoproducto")]
    [StringLength(50)]
    public string Codigoproducto { get; set; }

    [Required]
    [Column("nombreproducto")]
    [StringLength(255)]
    public string Nombreproducto { get; set; }

    [Column("cantidad")]
    public int Cantidad { get; set; }

    [Column("preciounitario", TypeName = "decimal(15, 4)")]
    public decimal Preciounitario { get; set; }

    [Column("ventasafectas", TypeName = "decimal(15, 2)")]
    public decimal Ventasafectas { get; set; }

    [Column("iva", TypeName = "decimal(15, 2)")]
    public decimal? Iva { get; set; }

    [Column("total_linea", TypeName = "decimal(15, 2)")]
    public decimal TotalLinea { get; set; }

    [Column("categoriaid")]
    public long Categoriaid { get; set; }

    [Required]
    [Column("nombrecategoria")]
    [StringLength(255)]
    public string Nombrecategoria { get; set; }
}