// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DepositoDental.Models.Entities;

[Keyless]
public partial class VwRolesConPermiso
{
    [Column("rolid")]
    public long Rolid { get; set; }

    [Required]
    [Column("nombrerol")]
    [StringLength(255)]
    public string Nombrerol { get; set; }

    [Column("permisoid")]
    public long Permisoid { get; set; }

    [Required]
    [Column("nombrepermiso")]
    [StringLength(255)]
    public string Nombrepermiso { get; set; }

    [Required]
    [Column("modulo")]
    [StringLength(100)]
    public string Modulo { get; set; }

    [Required]
    [Column("accion")]
    [StringLength(50)]
    public string Accion { get; set; }
}