// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DepositoDental.Models.Entities;

[Keyless]
public partial class VwUsuariosConRole
{
    [Column("usuarioid")]
    public long Usuarioid { get; set; }

    [Required]
    [Column("nombreusuario")]
    [StringLength(255)]
    public string Nombreusuario { get; set; }

    [Required]
    [Column("correoelectronico")]
    [StringLength(255)]
    public string Correoelectronico { get; set; }

    [Required]
    [Column("primernombre")]
    [StringLength(100)]
    public string Primernombre { get; set; }

    [Required]
    [Column("primerapellido")]
    [StringLength(100)]
    public string Primerapellido { get; set; }

    [Column("rolid")]
    public long Rolid { get; set; }

    [Required]
    [Column("nombrerol")]
    [StringLength(255)]
    public string Nombrerol { get; set; }
}