// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using DepositoDental.Models.Entities;
namespace DepositoDental.DataAccess;

public partial class AppDbContext : DbContext
{
    public AppDbContext(DbContextOptions<AppDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<CatEstado> CatEstados { get; set; }

    public virtual DbSet<CatTiposcliente> CatTiposclientes { get; set; }

    public virtual DbSet<CatTiposdireccion> CatTiposdireccions { get; set; }

    public virtual DbSet<CatTiposdocumento> CatTiposdocumentos { get; set; }

    public virtual DbSet<CliCliente> CliClientes { get; set; }

    public virtual DbSet<CliContactoscliente> CliContactosclientes { get; set; }

    public virtual DbSet<CliDireccionescliente> CliDireccionesclientes { get; set; }

    public virtual DbSet<ComOrdenescompra> ComOrdenescompras { get; set; }

    public virtual DbSet<ComOrdenescompradetalle> ComOrdenescompradetalles { get; set; }

    public virtual DbSet<CtaAsientoscontable> CtaAsientoscontables { get; set; }

    public virtual DbSet<CtaAsientosdetalle> CtaAsientosdetalles { get; set; }

    public virtual DbSet<CtaPeriodoscontable> CtaPeriodoscontables { get; set; }

    public virtual DbSet<CtaPlancontable> CtaPlancontables { get; set; }

    public virtual DbSet<GeoDepartamento> GeoDepartamentos { get; set; }

    public virtual DbSet<GeoMunicipio> GeoMunicipios { get; set; }

    public virtual DbSet<GeoPaise> GeoPaises { get; set; }

    public virtual DbSet<InvBodega> InvBodegas { get; set; }

    public virtual DbSet<InvCategoria> InvCategorias { get; set; }

    public virtual DbSet<InvLote> InvLotes { get; set; }

    public virtual DbSet<InvMarca> InvMarcas { get; set; }

    public virtual DbSet<InvMovimiento> InvMovimientos { get; set; }

    public virtual DbSet<InvMovimientosdetalle> InvMovimientosdetalles { get; set; }

    public virtual DbSet<InvProducto> InvProductos { get; set; }

    public virtual DbSet<InvProductosHistorico> InvProductosHistoricos { get; set; }

    public virtual DbSet<InvStockbodega> InvStockbodegas { get; set; }

    public virtual DbSet<InvTiposmovimiento> InvTiposmovimientos { get; set; }

    public virtual DbSet<InvUbicacione> InvUbicaciones { get; set; }

    public virtual DbSet<InvUnidadesmedidum> InvUnidadesmedida { get; set; }

    public virtual DbSet<PrvProveedore> PrvProveedores { get; set; }

    public virtual DbSet<RrhCargo> RrhCargos { get; set; }

    public virtual DbSet<RrhEmpleado> RrhEmpleados { get; set; }

    public virtual DbSet<RrhPlanilla> RrhPlanillas { get; set; }

    public virtual DbSet<RrhPlanillasdetalle> RrhPlanillasdetalles { get; set; }

    public virtual DbSet<RrhTiposplanilla> RrhTiposplanillas { get; set; }

    public virtual DbSet<SecPermiso> SecPermisos { get; set; }

    public virtual DbSet<SecRole> SecRoles { get; set; }

    public virtual DbSet<SecRolpermiso> SecRolpermisos { get; set; }

    public virtual DbSet<SecSesione> SecSesiones { get; set; }

    public virtual DbSet<SecUsuario> SecUsuarios { get; set; }

    public virtual DbSet<SecUsuariorole> SecUsuarioroles { get; set; }

    public virtual DbSet<VenCondicionespago> VenCondicionespagos { get; set; }

    public virtual DbSet<VenCotizacione> VenCotizaciones { get; set; }

    public virtual DbSet<VenCotizacionesdetalle> VenCotizacionesdetalles { get; set; }

    public virtual DbSet<VenFactura> VenFacturas { get; set; }

    public virtual DbSet<VenFacturasdetalle> VenFacturasdetalles { get; set; }

    public virtual DbSet<VenNotascredito> VenNotascreditos { get; set; }

    public virtual DbSet<VenPedido> VenPedidos { get; set; }

    public virtual DbSet<VenPedidosdetalle> VenPedidosdetalles { get; set; }

    public virtual DbSet<VenSeries> VenSeries { get; set; }

    public virtual DbSet<VwAnalisisVentasPorVendedor> VwAnalisisVentasPorVendedors { get; set; }

    public virtual DbSet<VwAsientosContablesResuman> VwAsientosContablesResumen { get; set; }

    public virtual DbSet<VwClientesCompleto> VwClientesCompletos { get; set; }

    public virtual DbSet<VwControlLotesVencimiento> VwControlLotesVencimientos { get; set; }

    public virtual DbSet<VwCotizacionesResuman> VwCotizacionesResumen { get; set; }

    public virtual DbSet<VwEmpleadosActivo> VwEmpleadosActivos { get; set; }

    public virtual DbSet<VwFacturasResuman> VwFacturasResumen { get; set; }

    public virtual DbSet<VwMovimientosInventario> VwMovimientosInventarios { get; set; }

    public virtual DbSet<VwNotasCreditoResuman> VwNotasCreditoResumen { get; set; }

    public virtual DbSet<VwOrdenesCompraResuman> VwOrdenesCompraResumen { get; set; }

    public virtual DbSet<VwPedidosResuman> VwPedidosResumen { get; set; }

    public virtual DbSet<VwProductosCompleto> VwProductosCompletos { get; set; }

    public virtual DbSet<VwProveedoresCompleto> VwProveedoresCompletos { get; set; }

    public virtual DbSet<VwReporteFacturacion> VwReporteFacturacions { get; set; }

    public virtual DbSet<VwReporteFacturacionDetallado> VwReporteFacturacionDetallados { get; set; }

    public virtual DbSet<VwReporteInventario> VwReporteInventarios { get; set; }

    public virtual DbSet<VwReporteInventarioDetallado> VwReporteInventarioDetallados { get; set; }

    public virtual DbSet<VwReporteVentasVendedor> VwReporteVentasVendedors { get; set; }

    public virtual DbSet<VwRolesConPermiso> VwRolesConPermisos { get; set; }

    public virtual DbSet<VwUsuariosConRole> VwUsuariosConRoles { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<CatEstado>(entity =>
        {
            entity.HasKey(e => e.Estadoid).HasName("PK__cat_esta__C6940F1BF1CA0324");
        });

        modelBuilder.Entity<CatTiposcliente>(entity =>
        {
            entity.HasKey(e => e.Tipoclienteid).HasName("PK__cat_tipo__1E7D6F4809F36976");

            entity.Property(e => e.Descuentodefecto).HasDefaultValue(0m);
        });

        modelBuilder.Entity<CatTiposdireccion>(entity =>
        {
            entity.HasKey(e => e.Tipodireccionid).HasName("PK__cat_tipo__09D4307C1F978B56");
        });

        modelBuilder.Entity<CatTiposdocumento>(entity =>
        {
            entity.HasKey(e => e.Tipodocumentoid).HasName("PK__cat_tipo__B05670DF7BD59C33");

            entity.Property(e => e.Activo).HasDefaultValue(true);
            entity.Property(e => e.Afectacontabilidad).HasDefaultValue(true);
            entity.Property(e => e.Escreditofiscal).HasDefaultValue(false);
        });

        modelBuilder.Entity<CliCliente>(entity =>
        {
            entity.HasKey(e => e.Clienteid).HasName("PK__cli_clie__C2FE2075CDABADE3");

            entity.ToTable("cli_clientes", tb =>
                {
                    tb.HasTrigger("trg_generar_codigo_cliente");
                    tb.HasTrigger("trg_prevenir_delete_cliente");
                });

            entity.HasIndex(e => e.Dui, "IX_cli_clientes_dui").HasFilter("([dui] IS NOT NULL)");

            entity.HasIndex(e => e.Nit, "IX_cli_clientes_nit").HasFilter("([nit] IS NOT NULL)");

            entity.Property(e => e.Activo).HasDefaultValue(true);
            entity.Property(e => e.Creditolimitado).HasDefaultValue(0m);
            entity.Property(e => e.Diasplazocredito).HasDefaultValue(0);
            entity.Property(e => e.Escontribuyente).HasDefaultValue(false);
            entity.Property(e => e.Fechacreacion).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.Municipio).WithMany(p => p.CliClientes).HasConstraintName("FK__cli_clien__munic__778AC167");

            entity.HasOne(d => d.Tipocliente).WithMany(p => p.CliClientes)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__cli_clien__tipoc__76969D2E");

            entity.HasOne(d => d.UsuariocreacionNavigation).WithMany(p => p.CliClientes).HasConstraintName("FK__cli_clien__usuar__787EE5A0");
        });

        modelBuilder.Entity<CliContactoscliente>(entity =>
        {
            entity.HasKey(e => e.Contactoid).HasName("PK__cli_cont__0ECDA18F801994CC");

            entity.Property(e => e.Esprincipal).HasDefaultValue(false);

            entity.HasOne(d => d.Cliente).WithMany(p => p.CliContactosclientes).HasConstraintName("FK__cli_conta__clien__01142BA1");
        });

        modelBuilder.Entity<CliDireccionescliente>(entity =>
        {
            entity.HasKey(e => e.Direccionid).HasName("PK__cli_dire__9F5D60D3F0ACDBA4");

            entity.Property(e => e.Esprincipal).HasDefaultValue(false);

            entity.HasOne(d => d.Cliente).WithMany(p => p.CliDireccionesclientes).HasConstraintName("FK__cli_direc__clien__7C4F7684");

            entity.HasOne(d => d.Municipio).WithMany(p => p.CliDireccionesclientes).HasConstraintName("FK__cli_direc__munic__7D439ABD");

            entity.HasOne(d => d.TipodireccionNavigation).WithMany(p => p.CliDireccionesclientes).HasConstraintName("FK_cli_direcciones_tipo");
        });

        modelBuilder.Entity<ComOrdenescompra>(entity =>
        {
            entity.HasKey(e => e.Ordencompraid).HasName("PK__com_orde__E38A5C4792B35A22");

            entity.Property(e => e.Total).HasDefaultValue(0m);

            entity.HasOne(d => d.Estado).WithMany(p => p.ComOrdenescompras)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__com_orden__estad__5224328E");

            entity.HasOne(d => d.Proveedor).WithMany(p => p.ComOrdenescompras)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__com_orden__prove__51300E55");

            entity.HasOne(d => d.UsuariocreacionNavigation).WithMany(p => p.ComOrdenescompras)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__com_orden__usuar__531856C7");
        });

        modelBuilder.Entity<ComOrdenescompradetalle>(entity =>
        {
            entity.HasKey(e => e.Ordencompradetalleid).HasName("PK__com_orde__AC944A4D829F301D");

            entity.HasOne(d => d.Ordencompra).WithMany(p => p.ComOrdenescompradetalles).HasConstraintName("FK__com_orden__orden__55F4C372");

            entity.HasOne(d => d.Producto).WithMany(p => p.ComOrdenescompradetalles)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__com_orden__produ__56E8E7AB");
        });

        modelBuilder.Entity<CtaAsientoscontable>(entity =>
        {
            entity.HasKey(e => e.Asientoid).HasName("PK__cta_asie__6EB2114002F4489E");

            entity.Property(e => e.Totaldebe).HasDefaultValue(0m);
            entity.Property(e => e.Totalhaber).HasDefaultValue(0m);

            entity.HasOne(d => d.Estado).WithMany(p => p.CtaAsientoscontables)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__cta_asien__estad__3DE82FB7");

            entity.HasOne(d => d.Periodo).WithMany(p => p.CtaAsientoscontables)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__cta_asien__perio__3CF40B7E");
        });

        modelBuilder.Entity<CtaAsientosdetalle>(entity =>
        {
            entity.HasKey(e => e.Asientodetalleid).HasName("PK__cta_asie__14B7334C662DDE3C");

            entity.Property(e => e.Debe).HasDefaultValue(0m);
            entity.Property(e => e.Haber).HasDefaultValue(0m);

            entity.HasOne(d => d.Asiento).WithMany(p => p.CtaAsientosdetalles).HasConstraintName("FK__cta_asien__asien__42ACE4D4");

            entity.HasOne(d => d.Cuenta).WithMany(p => p.CtaAsientosdetalles)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__cta_asien__cuent__43A1090D");
        });

        modelBuilder.Entity<CtaPeriodoscontable>(entity =>
        {
            entity.HasKey(e => e.Periodoid).HasName("PK__cta_peri__16231C4BF75867ED");

            entity.Property(e => e.Cerrado).HasDefaultValue(false);
        });

        modelBuilder.Entity<CtaPlancontable>(entity =>
        {
            entity.HasKey(e => e.Cuentaid).HasName("PK__cta_plan__1809BD5A66616F87");

            entity.Property(e => e.Naturaleza).IsFixedLength();

            entity.HasOne(d => d.Cuentapadre).WithMany(p => p.InverseCuentapadre).HasConstraintName("FK__cta_planc__cuent__32767D0B");
        });

        modelBuilder.Entity<GeoDepartamento>(entity =>
        {
            entity.HasKey(e => e.Departamentoid).HasName("PK__geo_depa__A67BDD502BA34940");

            entity.Property(e => e.Activo).HasDefaultValue(true);

            entity.HasOne(d => d.Pais).WithMany(p => p.GeoDepartamentos)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__geo_depar__paisi__3E52440B");
        });

        modelBuilder.Entity<GeoMunicipio>(entity =>
        {
            entity.HasKey(e => e.Municipioid).HasName("PK__geo_muni__CBC19639BB0E2A5E");

            entity.Property(e => e.Activo).HasDefaultValue(true);

            entity.HasOne(d => d.Departamento).WithMany(p => p.GeoMunicipios)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__geo_munic__depar__4316F928");
        });

        modelBuilder.Entity<GeoPaise>(entity =>
        {
            entity.HasKey(e => e.Paisid).HasName("PK__geo_pais__456747A3C68A2F6B");

            entity.Property(e => e.Activo).HasDefaultValue(true);
        });

        modelBuilder.Entity<InvBodega>(entity =>
        {
            entity.HasKey(e => e.Bodegaid).HasName("PK__inv_bode__D347C0DCDC15A367");

            entity.Property(e => e.Esprincipal).HasDefaultValue(false);
        });

        modelBuilder.Entity<InvCategoria>(entity =>
        {
            entity.HasKey(e => e.Categoriaid).HasName("PK__inv_cate__6367D408B992E420");

            entity.HasOne(d => d.Categoriapadre).WithMany(p => p.InverseCategoriapadre).HasConstraintName("FK__inv_categ__categ__0D7A0286");
        });

        modelBuilder.Entity<InvLote>(entity =>
        {
            entity.HasKey(e => e.Loteid).HasName("PK__inv_lote__28953B501EA645AF");

            entity.Property(e => e.Stockactual).HasDefaultValue(0);

            entity.HasOne(d => d.Producto).WithMany(p => p.InvLotes)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__inv_lotes__produ__3A4CA8FD");
        });

        modelBuilder.Entity<InvMarca>(entity =>
        {
            entity.HasKey(e => e.Marcaid).HasName("PK__inv_marc__CA3F627F9098EDF7");
        });

        modelBuilder.Entity<InvMovimiento>(entity =>
        {
            entity.HasKey(e => e.Movimientoid).HasName("PK__inv_movi__9669F8D1EC52AB3B");

            entity.Property(e => e.Fechamovimiento).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.Bodegadestino).WithMany(p => p.InvMovimientoBodegadestinos).HasConstraintName("FK__inv_movim__bodeg__44CA3770");

            entity.HasOne(d => d.Bodegaorigen).WithMany(p => p.InvMovimientoBodegaorigens).HasConstraintName("FK__inv_movim__bodeg__43D61337");

            entity.HasOne(d => d.Estado).WithMany(p => p.InvMovimientos)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__inv_movim__estad__45BE5BA9");

            entity.HasOne(d => d.Tipomovimiento).WithMany(p => p.InvMovimientos)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__inv_movim__tipom__42E1EEFE");

            entity.HasOne(d => d.UsuariocreacionNavigation).WithMany(p => p.InvMovimientos)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__inv_movim__usuar__46B27FE2");
        });

        modelBuilder.Entity<InvMovimientosdetalle>(entity =>
        {
            entity.HasKey(e => e.Movimientodetalleid).HasName("PK__inv_movi__D7259812B39CE288");

            entity.ToTable("inv_movimientosdetalle", tb =>
                {
                    tb.HasTrigger("tr_ActualizarStock");
                    tb.HasTrigger("tr_ActualizarStockCompleto");
                });

            entity.Property(e => e.Costounitario).HasDefaultValue(0m);

            entity.HasOne(d => d.Lote).WithMany(p => p.InvMovimientosdetalles).HasConstraintName("FK__inv_movim__lotei__4C6B5938");

            entity.HasOne(d => d.Movimiento).WithMany(p => p.InvMovimientosdetalles).HasConstraintName("FK__inv_movim__movim__4A8310C6");

            entity.HasOne(d => d.Producto).WithMany(p => p.InvMovimientosdetalles)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__inv_movim__produ__4B7734FF");
        });

        modelBuilder.Entity<InvProducto>(entity =>
        {
            entity.HasKey(e => e.Productoid).HasName("PK__inv_prod__69E7E57C35A8E101");

            entity.ToTable("inv_productos", tb =>
                {
                    tb.HasTrigger("tr_HistorialProductos");
                    tb.HasTrigger("trg_auditar_cambios_producto");
                    tb.HasTrigger("trg_generar_codigo_producto");
                    tb.HasTrigger("trg_prevenir_delete_producto");
                });

            entity.HasIndex(e => e.Codigobarras, "IX_inv_productos_codigobarras").HasFilter("([codigobarras] IS NOT NULL)");

            entity.Property(e => e.Activo).HasDefaultValue(true);
            entity.Property(e => e.Aplicaiva).HasDefaultValue(true);
            entity.Property(e => e.Costopromedio).HasDefaultValue(0m);
            entity.Property(e => e.Esservicio).HasDefaultValue(false);
            entity.Property(e => e.Manejalotes).HasDefaultValue(false);
            entity.Property(e => e.Manejavencimiento).HasDefaultValue(false);
            entity.Property(e => e.Porcentajeiva).HasDefaultValue(13.00m);
            entity.Property(e => e.Precioventa1).HasDefaultValue(0m);
            entity.Property(e => e.Precioventa2).HasDefaultValue(0m);
            entity.Property(e => e.Precioventa3).HasDefaultValue(0m);
            entity.Property(e => e.Stockactual).HasDefaultValue(0);
            entity.Property(e => e.Stockcomprometido).HasDefaultValue(0);
            entity.Property(e => e.Stockmaximo).HasDefaultValue(0);
            entity.Property(e => e.Stockminimo).HasDefaultValue(0);

            entity.HasOne(d => d.Categoria).WithMany(p => p.InvProductos)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__inv_produ__categ__2CF2ADDF");

            entity.HasOne(d => d.Marca).WithMany(p => p.InvProductos).HasConstraintName("FK__inv_produ__marca__2DE6D218");

            entity.HasOne(d => d.Unidadmedida).WithMany(p => p.InvProductos)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__inv_produ__unida__2EDAF651");
        });

        modelBuilder.Entity<InvProductosHistorico>(entity =>
        {
            entity.HasKey(e => e.Historicoid).HasName("PK__inv_prod__22D49FAD856F43F6");

            entity.Property(e => e.Fechacambio).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.Producto).WithMany(p => p.InvProductosHistoricos)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__inv_produ__produ__6E8B6712");

            entity.HasOne(d => d.Usuario).WithMany(p => p.InvProductosHistoricos).HasConstraintName("FK__inv_produ__usuar__6F7F8B4B");
        });

        modelBuilder.Entity<InvStockbodega>(entity =>
        {
            entity.HasKey(e => e.Stockbodegaid).HasName("PK__inv_stoc__1C8CBE032A3C5C53");

            entity.Property(e => e.Stockactual).HasDefaultValue(0);

            entity.HasOne(d => d.Bodega).WithMany(p => p.InvStockbodegas)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__inv_stock__bodeg__3493CFA7");

            entity.HasOne(d => d.Producto).WithMany(p => p.InvStockbodegas)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__inv_stock__produ__339FAB6E");

            entity.HasOne(d => d.Ubicacion).WithMany(p => p.InvStockbodegas).HasConstraintName("FK__inv_stock__ubica__3587F3E0");
        });

        modelBuilder.Entity<InvTiposmovimiento>(entity =>
        {
            entity.HasKey(e => e.Tipomovimientoid).HasName("PK__inv_tipo__34A15D94E097ADAE");

            entity.Property(e => e.Tipooperacion).IsFixedLength();
        });

        modelBuilder.Entity<InvUbicacione>(entity =>
        {
            entity.HasKey(e => e.Ubicacionid).HasName("PK__inv_ubic__6A9A4F930C512C3E");

            entity.HasOne(d => d.Bodega).WithMany(p => p.InvUbicaciones)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__inv_ubica__bodeg__1AD3FDA4");
        });

        modelBuilder.Entity<InvUnidadesmedidum>(entity =>
        {
            entity.HasKey(e => e.Unidadmedidaid).HasName("PK__inv_unid__3486698D6099B3E1");
        });

        modelBuilder.Entity<PrvProveedore>(entity =>
        {
            entity.HasKey(e => e.Proveedorid).HasName("PK__prv_prov__8252297524E441ED");

            entity.ToTable("prv_proveedores", tb =>
                {
                    tb.HasTrigger("trg_generar_codigo_proveedor");
                    tb.HasTrigger("trg_prevenir_delete_proveedor");
                });

            entity.Property(e => e.Activo).HasDefaultValue(true);
            entity.Property(e => e.Fechacreacion).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.Pais).WithMany(p => p.PrvProveedores).HasConstraintName("FK__prv_prove__paisi__08B54D69");

            entity.HasOne(d => d.UsuariocreacionNavigation).WithMany(p => p.PrvProveedores).HasConstraintName("FK__prv_prove__usuar__09A971A2");
        });

        modelBuilder.Entity<RrhCargo>(entity =>
        {
            entity.HasKey(e => e.Cargoid).HasName("PK__rrh_carg__7E9E1A7D5DEB3E91");
        });

        modelBuilder.Entity<RrhEmpleado>(entity =>
        {
            entity.HasKey(e => e.Empleadoid).HasName("PK__rrh_empl__CCDA5420124799D0");

            entity.ToTable("rrh_empleados", tb => tb.HasTrigger("trg_generar_codigo_empleado"));

            entity.Property(e => e.Activo).HasDefaultValue(true);

            entity.HasOne(d => d.Cargo).WithMany(p => p.RrhEmpleados).HasConstraintName("FK__rrh_emple__cargo__2057CCD0");

            entity.HasOne(d => d.Municipio).WithMany(p => p.RrhEmpleados).HasConstraintName("FK__rrh_emple__munic__1F63A897");

            entity.HasOne(d => d.Usuario).WithMany(p => p.RrhEmpleados).HasConstraintName("FK__rrh_emple__usuar__214BF109");
        });

        modelBuilder.Entity<RrhPlanilla>(entity =>
        {
            entity.HasKey(e => e.Planillaid).HasName("PK__rrh_plan__8D79D80FFDF47A44");

            entity.Property(e => e.Totaldescuentos).HasDefaultValue(0m);
            entity.Property(e => e.Totalingresos).HasDefaultValue(0m);
            entity.Property(e => e.Totalpagar).HasDefaultValue(0m);

            entity.HasOne(d => d.Estado).WithMany(p => p.RrhPlanillas)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__rrh_plani__estad__2AD55B43");

            entity.HasOne(d => d.Tipoplanilla).WithMany(p => p.RrhPlanillas)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__rrh_plani__tipop__29E1370A");
        });

        modelBuilder.Entity<RrhPlanillasdetalle>(entity =>
        {
            entity.HasKey(e => e.Planilladetalleid).HasName("PK__rrh_plan__999848D4A554DE9B");

            entity.HasOne(d => d.Empleado).WithMany(p => p.RrhPlanillasdetalles)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__rrh_plani__emple__2EA5EC27");

            entity.HasOne(d => d.Planilla).WithMany(p => p.RrhPlanillasdetalles).HasConstraintName("FK__rrh_plani__plani__2DB1C7EE");
        });

        modelBuilder.Entity<RrhTiposplanilla>(entity =>
        {
            entity.HasKey(e => e.Tipoplanillaid).HasName("PK__rrh_tipo__55B4491CAB53A217");
        });

        modelBuilder.Entity<SecPermiso>(entity =>
        {
            entity.HasKey(e => e.Permisoid).HasName("PK__sec_perm__23B8D119014F5311");

            entity.Property(e => e.Activo).HasDefaultValue(true);
        });

        modelBuilder.Entity<SecRole>(entity =>
        {
            entity.HasKey(e => e.Rolid).HasName("PK__sec_role__5403326C13C2BB4F");

            entity.Property(e => e.Activo).HasDefaultValue(true);
        });

        modelBuilder.Entity<SecRolpermiso>(entity =>
        {
            entity.HasKey(e => e.Rolpermisoid).HasName("PK__sec_rolp__DEC719F094AC879C");

            entity.Property(e => e.Fechaasignacion).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.Permiso).WithMany(p => p.SecRolpermisos).HasConstraintName("FK__sec_rolpe__permi__571DF1D5");

            entity.HasOne(d => d.Rol).WithMany(p => p.SecRolpermisos).HasConstraintName("FK__sec_rolpe__rolid__5629CD9C");
        });

        modelBuilder.Entity<SecSesione>(entity =>
        {
            entity.HasKey(e => e.Sesionid).HasName("PK__sec_sesi__4DAEEBEC4D7EA0E4");

            entity.Property(e => e.Activa).HasDefaultValue(true);

            entity.HasOne(d => d.Usuario).WithMany(p => p.SecSesiones).HasConstraintName("FK__sec_sesio__usuar__619B8048");
        });

        modelBuilder.Entity<SecUsuario>(entity =>
        {
            entity.HasKey(e => e.Usuarioid).HasName("PK__sec_usua__A5B49E465A262CEA");

            entity.ToTable("sec_usuarios", tb => tb.HasTrigger("trg_prevenir_delete_usuario"));

            entity.Property(e => e.Activo).HasDefaultValue(true);
            entity.Property(e => e.Bloqueado).HasDefaultValue(false);
            entity.Property(e => e.Intentoslogin).HasDefaultValue(0);
        });

        modelBuilder.Entity<SecUsuariorole>(entity =>
        {
            entity.HasKey(e => e.Usuariorolid).HasName("PK__sec_usua__3E59D2D7B34C5156");

            entity.Property(e => e.Activo).HasDefaultValue(true);

            entity.HasOne(d => d.Rol).WithMany(p => p.SecUsuarioroles).HasConstraintName("FK__sec_usuar__rolid__5CD6CB2B");

            entity.HasOne(d => d.Usuario).WithMany(p => p.SecUsuarioroles).HasConstraintName("FK__sec_usuar__usuar__5BE2A6F2");
        });

        modelBuilder.Entity<VenCondicionespago>(entity =>
        {
            entity.HasKey(e => e.Condicionpagoid).HasName("PK__ven_cond__8B1D5D5786605E7C");
        });

        modelBuilder.Entity<VenCotizacione>(entity =>
        {
            entity.HasKey(e => e.Cotizacionid).HasName("PK__ven_coti__EF644F1C610052CE");

            entity.Property(e => e.Total).HasDefaultValue(0m);

            entity.HasOne(d => d.Cliente).WithMany(p => p.VenCotizaciones)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__ven_cotiz__clien__690797E6");

            entity.HasOne(d => d.Estado).WithMany(p => p.VenCotizaciones)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__ven_cotiz__estad__69FBBC1F");

            entity.HasOne(d => d.UsuariocreacionNavigation).WithMany(p => p.VenCotizaciones)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__ven_cotiz__usuar__6AEFE058");
        });

        modelBuilder.Entity<VenCotizacionesdetalle>(entity =>
        {
            entity.HasKey(e => e.Cotizaciondetalleid).HasName("PK__ven_coti__A4DA5AC3262E9AE2");

            entity.ToTable("ven_cotizacionesdetalles", tb => tb.HasTrigger("trg_actualizar_totales_cotizacion"));

            entity.Property(e => e.Descuentoporcentaje).HasDefaultValue(0m);

            entity.HasOne(d => d.Cotizacion).WithMany(p => p.VenCotizacionesdetalles).HasConstraintName("FK__ven_cotiz__cotiz__6EC0713C");

            entity.HasOne(d => d.Producto).WithMany(p => p.VenCotizacionesdetalles)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__ven_cotiz__produ__6FB49575");
        });

        modelBuilder.Entity<VenFactura>(entity =>
        {
            entity.HasKey(e => e.Facturaid).HasName("PK__ven_fact__AAFE0E097F76B67D");

            entity.ToTable("ven_facturas", tb =>
                {
                    tb.HasTrigger("trg_prevenir_delete_factura");
                    tb.HasTrigger("trg_revertir_stock_anulacion");
                });

            entity.Property(e => e.Anulada).HasDefaultValue(false);
            entity.Property(e => e.Descuento).HasDefaultValue(0m);
            entity.Property(e => e.Iva).HasDefaultValue(0m);
            entity.Property(e => e.Subtotal).HasDefaultValue(0m);
            entity.Property(e => e.Total).HasDefaultValue(0m);

            entity.HasOne(d => d.Cliente).WithMany(p => p.VenFacturas)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__ven_factu__clien__05A3D694");

            entity.HasOne(d => d.Condicionpago).WithMany(p => p.VenFacturas).HasConstraintName("FK__ven_factu__condi__0697FACD");

            entity.HasOne(d => d.Estado).WithMany(p => p.VenFacturas)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__ven_factu__estad__078C1F06");

            entity.HasOne(d => d.Serie).WithMany(p => p.VenFacturas)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__ven_factu__serie__03BB8E22");

            entity.HasOne(d => d.UsuariocreacionNavigation).WithMany(p => p.VenFacturas)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__ven_factu__usuar__0880433F");
        });

        modelBuilder.Entity<VenFacturasdetalle>(entity =>
        {
            entity.HasKey(e => e.Facturadetalleid).HasName("PK__ven_fact__66D71E54BD334A46");

            entity.ToTable("ven_facturasdetalles", tb =>
                {
                    tb.HasTrigger("trg_actualizar_stock_venta");
                    tb.HasTrigger("trg_actualizar_totales_factura");
                    tb.HasTrigger("trg_validar_stock_antes_de_venta");
                });

            entity.Property(e => e.Iva).HasDefaultValue(0m);

            entity.HasOne(d => d.Factura).WithMany(p => p.VenFacturasdetalles).HasConstraintName("FK__ven_factu__factu__0C50D423");

            entity.HasOne(d => d.Producto).WithMany(p => p.VenFacturasdetalles)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__ven_factu__produ__0D44F85C");
        });

        modelBuilder.Entity<VenNotascredito>(entity =>
        {
            entity.HasKey(e => e.Notacreditoid).HasName("PK__ven_nota__410409B0F29B9708");

            entity.Property(e => e.Total).HasDefaultValue(0m);

            entity.HasOne(d => d.Factura).WithMany(p => p.VenNotascreditos)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__ven_notas__factu__13F1F5EB");

            entity.HasOne(d => d.Serie).WithMany(p => p.VenNotascreditos)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__ven_notas__serie__12FDD1B2");

            entity.HasOne(d => d.UsuariocreacionNavigation).WithMany(p => p.VenNotascreditos)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__ven_notas__usuar__14E61A24");
        });

        modelBuilder.Entity<VenPedido>(entity =>
        {
            entity.HasKey(e => e.Pedidoid).HasName("PK__ven_pedi__BAFD077C79D58105");

            entity.Property(e => e.Total).HasDefaultValue(0m);

            entity.HasOne(d => d.Cliente).WithMany(p => p.VenPedidos)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__ven_pedid__clien__74794A92");

            entity.HasOne(d => d.Estado).WithMany(p => p.VenPedidos)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__ven_pedid__estad__756D6ECB");

            entity.HasOne(d => d.UsuariocreacionNavigation).WithMany(p => p.VenPedidos)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__ven_pedid__usuar__76619304");
        });

        modelBuilder.Entity<VenPedidosdetalle>(entity =>
        {
            entity.HasKey(e => e.Pedidodetalleid).HasName("PK__ven_pedi__E83A6AAE175039F8");

            entity.ToTable("ven_pedidosdetalle", tb => tb.HasTrigger("trg_actualizar_totales_pedido"));

            entity.HasOne(d => d.Pedido).WithMany(p => p.VenPedidosdetalles).HasConstraintName("FK__ven_pedid__pedid__793DFFAF");

            entity.HasOne(d => d.Producto).WithMany(p => p.VenPedidosdetalles)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__ven_pedid__produ__7A3223E8");
        });

        modelBuilder.Entity<VenSeries>(entity =>
        {
            entity.HasKey(e => e.Serieid).HasName("PK__ven_seri__688DC046CB637337");

            entity.Property(e => e.Activo).HasDefaultValue(true);
            entity.Property(e => e.Numeroactual).HasDefaultValue(1L);
        });

        modelBuilder.Entity<VwAnalisisVentasPorVendedor>(entity =>
        {
            entity.ToView("vw_AnalisisVentasPorVendedor");
        });

        modelBuilder.Entity<VwAsientosContablesResuman>(entity =>
        {
            entity.ToView("vw_AsientosContablesResumen");
        });

        modelBuilder.Entity<VwClientesCompleto>(entity =>
        {
            entity.ToView("vw_ClientesCompletos");
        });

        modelBuilder.Entity<VwControlLotesVencimiento>(entity =>
        {
            entity.ToView("vw_ControlLotesVencimiento");
        });

        modelBuilder.Entity<VwCotizacionesResuman>(entity =>
        {
            entity.ToView("vw_CotizacionesResumen");
        });

        modelBuilder.Entity<VwEmpleadosActivo>(entity =>
        {
            entity.ToView("vw_EmpleadosActivos");
        });

        modelBuilder.Entity<VwFacturasResuman>(entity =>
        {
            entity.ToView("vw_FacturasResumen");
        });

        modelBuilder.Entity<VwMovimientosInventario>(entity =>
        {
            entity.ToView("vw_MovimientosInventario");

            entity.Property(e => e.Tipooperacion).IsFixedLength();
        });

        modelBuilder.Entity<VwNotasCreditoResuman>(entity =>
        {
            entity.ToView("vw_NotasCreditoResumen");
        });

        modelBuilder.Entity<VwOrdenesCompraResuman>(entity =>
        {
            entity.ToView("vw_OrdenesCompraResumen");
        });

        modelBuilder.Entity<VwPedidosResuman>(entity =>
        {
            entity.ToView("vw_PedidosResumen");
        });

        modelBuilder.Entity<VwProductosCompleto>(entity =>
        {
            entity.ToView("vw_ProductosCompletos");
        });

        modelBuilder.Entity<VwProveedoresCompleto>(entity =>
        {
            entity.ToView("vw_ProveedoresCompletos");
        });

        modelBuilder.Entity<VwReporteFacturacion>(entity =>
        {
            entity.ToView("vw_ReporteFacturacion");
        });

        modelBuilder.Entity<VwReporteFacturacionDetallado>(entity =>
        {
            entity.ToView("vw_ReporteFacturacionDetallado");
        });

        modelBuilder.Entity<VwReporteInventario>(entity =>
        {
            entity.ToView("vw_ReporteInventario");
        });

        modelBuilder.Entity<VwReporteInventarioDetallado>(entity =>
        {
            entity.ToView("vw_ReporteInventarioDetallado");
        });

        modelBuilder.Entity<VwReporteVentasVendedor>(entity =>
        {
            entity.ToView("vw_ReporteVentasVendedor");
        });

        modelBuilder.Entity<VwRolesConPermiso>(entity =>
        {
            entity.ToView("vw_RolesConPermisos");
        });

        modelBuilder.Entity<VwUsuariosConRole>(entity =>
        {
            entity.ToView("vw_UsuariosConRoles");
        });
        modelBuilder.HasSequence("seq_pedidos");

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}